CREATE TABLE [dbo].[DEV_ERROR_Rows] (
    [DespatchId]                 INT             NULL,
    [RegionId]                   INT             NULL,
    [ClientId]                   INT             NULL,
    [AckDateTime]                DATETIME        NULL,
    [OnSiteDateTime]             DATETIME        NULL,
    [OffSiteDateTime]            DATETIME        NULL,
    [JobText]                    VARCHAR (MAX)   NULL,
    [PatrolResolution]           VARCHAR (MAX)   NULL,
    [AlarmDocketId]              INT             NULL,
    [DespatchTypeId]             INT             NULL,
    [PermanentPatrolCompletedId] INT             NULL,
    [DespatchZone1Id]            INT             NULL,
    [DespatchZone2Id]            INT             NULL,
    [PatrolOfficerEmployee1Id]   INT             NULL,
    [MonitoringStationId]        INT             NULL,
    [PermanentPatrolId]          INT             NULL,
    [OnsiteLat]                  VARCHAR (64)    NULL,
    [OnsiteLong]                 VARCHAR (64)    NULL,
    [OnsiteDistanceFromSite]     VARCHAR (64)    NULL,
    [Code]                       VARCHAR (64)    NULL,
    [Description]                VARCHAR (128)   NULL,
    [DespatchDateTime]           DATETIME        NULL,
    [SpecialInstructions]        VARCHAR (MAX)   NULL,
    [Hazards]                    VARCHAR (MAX)   NULL,
    [TimeOnSiteInMinutes]        INT             NULL,
    [DespatchZoneId]             INT             NULL,
    [Zone Name]                  VARCHAR (128)   NULL,
    [zoneBranch]                 VARCHAR (128)   NULL,
    [TotalCount]                 INT             NULL,
    [MissedCount]                INT             NULL,
    [patrolValue]                NUMERIC (10, 2) NULL
);

