CREATE TABLE [dbo].[DIMREGION] (
    [SK_DIM_REGION]       INT           IDENTITY (1, 1) NOT NULL,
    [PK_REGIONCODE]       VARCHAR (50)  NULL,
    [P_REGIONNAME]        VARCHAR (100) NULL,
    [MD_DATELASTMODIFIED] DATETIME      NULL,
    [MD_ETLJOB]           BIGINT        NULL,
    [MD_ETLEXECUTION]     BIGINT        NULL,
    [MD_ETLRUN]           BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_REGION] ASC)
);

