CREATE TABLE [lookup].[Client_TEMP] (
    [ClientId]                                INT             NULL,
    [EntryClerkUserId]                        INT             NULL,
    [EntryDateTimeStart]                      DATETIME        NULL,
    [EntryDateTimeEnd]                        DATETIME        NULL,
    [IsComplete]                              BIT             NULL,
    [Status]                                  BIT             NULL,
    [ClientIDCode]                            VARCHAR (128)   NULL,
    [BureauId]                                INT             NULL,
    [Site]                                    VARCHAR (256)   NULL,
    [Address1]                                VARCHAR (128)   NULL,
    [Address2]                                VARCHAR (128)   NULL,
    [AddressSuburbId]                         INT             NULL,
    [AddressXStreet]                          VARCHAR (128)   NULL,
    [PhoneNo]                                 VARCHAR (128)   NULL,
    [FaxNo]                                   VARCHAR (128)   NULL,
    [DebtorCode]                              VARCHAR (64)    NULL,
    [CurrentPatrolStartDate]                  DATETIME        NULL,
    [CurrentPatrolEndDate]                    DATETIME        NULL,
    [Comments]                                VARCHAR (MAX)   NULL,
    [ChargeRateId]                            INT             NULL,
    [ChargeRateOverriden]                     BIT             NULL,
    [ChargeRateLastChangedDate]               DATETIME        NULL,
    [ChargeRateLastChangedByUserId]           INT             NULL,
    [ChargeRateLastChangeReason]              VARCHAR (MAX)   NULL,
    [SpecialInstructions]                     VARCHAR (MAX)   NULL,
    [DefaultChargeRate]                       NUMERIC (10, 2) NULL,
    [ChargePeriod]                            SMALLINT        NULL,
    [AdditionalChargeAmount]                  NUMERIC (10, 2) NULL,
    [AdditionalChargePeriod]                  SMALLINT        NULL,
    [DaySurcharge]                            NUMERIC (10, 2) NULL,
    [ORTDiscount]                             NUMERIC (10, 2) NULL,
    [ResponseTimeDay]                         SMALLINT        NULL,
    [ResponseTimeNight]                       SMALLINT        NULL,
    [ResponseTimeWeekend]                     SMALLINT        NULL,
    [ChargeRateComments]                      VARCHAR (MAX)   NULL,
    [ZoneId]                                  VARCHAR (128)   NULL,
    [AlarmType]                               VARCHAR (128)   NULL,
    [PanelType]                               VARCHAR (128)   NULL,
    [PanelCode]                               VARCHAR (128)   NULL,
    [PanelLocation]                           VARCHAR (128)   NULL,
    [MonitoringStationId]                     INT             NULL,
    [AttachmentDescription]                   VARCHAR (MAX)   NULL,
    [HasKeys]                                 VARCHAR (3)     NULL,
    [LastAlarmResponseDate]                   DATETIME        NULL,
    [LastContactDate]                         DATETIME        NULL,
    [IsSuspended]                             BIT             NULL,
    [SuspendedDate]                           DATETIME        NULL,
    [SuspendedUserId]                         INT             NULL,
    [SuspendedReason]                         VARCHAR (128)   NULL,
    [RegionId]                                INT             NULL,
    [CostCentre]                              VARCHAR (64)    NULL,
    [GLcode]                                  VARCHAR (64)    NULL,
    [NewClientNotificationEmailSentDate]      DATETIME        NULL,
    [PrimarySubContractorId]                  INT             NULL,
    [BackupSubContractorId]                   INT             NULL,
    [ZoneId2]                                 VARCHAR (128)   NULL,
    [GLOverrideFormat]                        INT             NULL,
    [Hazards]                                 VARCHAR (MAX)   NULL,
    [PermanentPatrolRatePerMinute]            NUMERIC (10, 2) NULL,
    [CasualPatrolRateExGST]                   NUMERIC (10, 2) NULL,
    [PatrolTotalEstRevenue]                   NUMERIC (10, 2) NULL,
    [CostCentreCasualPatrol]                  VARCHAR (64)    NULL,
    [GLcodeCasualPatrol]                      VARCHAR (64)    NULL,
    [CostCentrePermPatrol]                    VARCHAR (64)    NULL,
    [GLcodePermPatrol]                        VARCHAR (64)    NULL,
    [MapLat]                                  FLOAT (53)      NULL,
    [MapLong]                                 FLOAT (53)      NULL,
    [AdditionalKeyComments]                   VARCHAR (MAX)   NULL,
    [ServicesPrimarySubContractorId]          INT             NULL,
    [ServicesPrimaryDespatchZoneId]           INT             NULL,
    [CostCentreServices]                      VARCHAR (64)    NULL,
    [CostCentreMonitoring]                    VARCHAR (64)    NULL,
    [CostCentreMaintenance]                   VARCHAR (64)    NULL,
    [GLcodeServices]                          VARCHAR (64)    NULL,
    [GLcodeMonitoring]                        VARCHAR (64)    NULL,
    [GLcodeMaintenance]                       VARCHAR (64)    NULL,
    [GSTFlag]                                 INT             NULL,
    [VoiceCode]                               VARCHAR (64)    NULL,
    [PreviousStatus]                          BIT             NULL,
    [SendPatrolVerificationEmail]             BIT             NULL,
    [SendRFCNoteEmail]                        BIT             NULL,
    [PreferredServiceProvider]                INT             NULL,
    [SendPatrolResolutionEmail]               BIT             NULL,
    [CasualPatrolRateType]                    INT             NULL,
    [InstallerCode]                           VARCHAR (128)   NULL,
    [AlarmMinTimeOnSite]                      INT             NULL,
    [SuburbLocationId]                        INT             NULL,
    [ClientServiceManagerOverridden]          BIT             NULL,
    [ClientServiceManagerUserId]              INT             NULL,
    [ClientServiceManagerLastVisitedDateTime] DATETIME        NULL,
    [AOMDaySubcontractorId]                   INT             NULL,
    [AOMNightSubcontractorId]                 INT             NULL,
    [OriginalSourceID]                        INT             NULL,
    [OriginalSourceDebtorCode]                VARCHAR (64)    NULL,
    [OriginalSourceCostCentre]                VARCHAR (64)    NULL,
    [ABN]                                     VARCHAR (11)    NULL,
    [PostalCode]                              VARCHAR (64)    NULL,
    [City]                                    VARCHAR (128)   NULL,
    [OverrideABNValidation]                   BIT             NULL,
    [BillingLandmarkItemId]                   INT             NULL,
    [DistanceFromBillingLandmark]             NUMERIC (10, 2) NULL,
    [AutoDespatchRule]                        INT             NULL
);

