CREATE TABLE [ods].[FCT_GLBUDGET_NEW] (
    [id]        INT             IDENTITY (1, 1) NOT NULL,
    [periodOid] VARCHAR (34)    NULL,
    [jobOid]    VARCHAR (34)    NULL,
    [orgOid]    VARCHAR (34)    NULL,
    [glOid]     VARCHAR (34)    NULL,
    [total]     NUMERIC (14, 2) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_FCT_GLBUDGET_NEW_DIM_GT_GL] FOREIGN KEY ([glOid]) REFERENCES [ods].[DIM_GT_GL] ([oid]),
    CONSTRAINT [FK_FCT_GLBUDGET_NEW_DIM_GT_PERIOD] FOREIGN KEY ([periodOid]) REFERENCES [ods].[DIM_GT_PERIOD] ([oid]),
    CONSTRAINT [FK_FCT_GLBUDGET_NEW_DIM_JOB] FOREIGN KEY ([jobOid]) REFERENCES [ods].[DIM_JOB] ([oid]),
    CONSTRAINT [FK_FCT_GLBUDGET_NEW_DIM_ORGANISATION] FOREIGN KEY ([orgOid]) REFERENCES [ods].[DIM_ORGANISATION] ([oid])
);

