CREATE TABLE [ods].[FCT_ROSTER] (
    [PKAssign]         VARCHAR (15)     NOT NULL,
    [assignmentId]     BIGINT           NOT NULL,
    [itStaffId]        NVARCHAR (255)   NULL,
    [dateFrom]         DATETIME         NOT NULL,
    [dateTo]           DATETIME         NULL,
    [enteredHours]     NUMERIC (28, 10) NULL,
    [itCustomer]       NVARCHAR (255)   NULL,
    [itLocation]       NVARCHAR (255)   NULL,
    [itSubLocation]    NVARCHAR (255)   NULL,
    [noCharge]         NVARCHAR (20)    NULL,
    [branchID]         INT              NULL,
    [bsid]             INT              NULL,
    [customerOid]      VARCHAR (34)     NULL,
    [payrollTransType] NVARCHAR (255)   NULL,
    [leaveName]        NVARCHAR (255)   NULL,
    [jobOid]           VARCHAR (34)     NULL,
    [billActivityOid]  VARCHAR (34)     NULL,
    [assignmentDate]   DATE             NULL,
    [lastModified]     DATETIME         NULL,
    [created]          DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([PKAssign] ASC),
    CONSTRAINT [FK_FCT_ROSTER_DIM_BRANCH] FOREIGN KEY ([branchID]) REFERENCES [ods].[DIM_BRANCH] ([id]),
    CONSTRAINT [FK_FCT_ROSTER_DIM_BUSINESS] FOREIGN KEY ([bsid]) REFERENCES [ods].[DIM_BUSINESS] ([id]),
    CONSTRAINT [FK_FCT_ROSTER_DIM_GT_ACTIVITY] FOREIGN KEY ([billActivityOid]) REFERENCES [ods].[DIM_GT_ACTIVITY] ([oid]),
    CONSTRAINT [FK_FCT_ROSTER_DIM_JOB] FOREIGN KEY ([jobOid]) REFERENCES [ods].[DIM_JOB] ([oid]),
    CONSTRAINT [FK_FCT_ROSTER_DIM_ORGANISATION] FOREIGN KEY ([customerOid]) REFERENCES [ods].[DIM_ORGANISATION] ([oid])
);

