CREATE TABLE [ods].[STG_WS_EMPLOYEE] (
    [EmployeeId]            INT           NOT NULL,
    [Code]                  VARCHAR (128) NULL,
    [OccupationId]          INT           NULL,
    [Title]                 VARCHAR (16)  NULL,
    [Employed]              BIT           NULL,
    [FirstName]             VARCHAR (128) NULL,
    [OtherName]             VARCHAR (128) NULL,
    [LastName]              VARCHAR (128) NULL,
    [DOB]                   DATETIME      NULL,
    [EmailAddress]          VARCHAR (MAX) NULL,
    [ContactPhoneNo]        VARCHAR (128) NULL,
    [AltContactPhoneNo]     VARCHAR (128) NULL,
    [Gender]                BIT           NULL,
    [EmploymentStartDate]   DATETIME      NULL,
    [EmploymentEndDate]     DATETIME      NULL,
    [ReportsToEmployeeId]   INT           NULL,
    [Comments]              VARCHAR (MAX) NULL,
    [UserId]                INT           NULL,
    [RegionId]              INT           NULL,
    [StateId]               INT           NULL,
    [Password]              VARCHAR (128) NULL,
    [LicenceNo]             VARCHAR (128) NULL,
    [LicenceExpiryDate]     DATETIME      NULL,
    [StaffID]               VARCHAR (128) NULL,
    [StaffRoleID]           INT           NULL,
    [DespatchZoneOption]    INT           NULL,
    [ActiveDirectorySource] INT           NULL,
    [PIN]                   VARCHAR (16)  NULL,
    PRIMARY KEY CLUSTERED ([EmployeeId] ASC)
);

