CREATE TABLE [ods].[STG_WS_SUBCONTRACTOR] (
    [SubContractorId]                        INT           NOT NULL,
    [SubContractorCode]                      VARCHAR (16)  NULL,
    [Status]                                 BIT           NULL,
    [Name]                                   VARCHAR (128) NULL,
    [Address1]                               VARCHAR (128) NULL,
    [Address2]                               VARCHAR (128) NULL,
    [SuburbId]                               INT           NULL,
    [PhoneNo]                                VARCHAR (128) NULL,
    [FaxNo]                                  VARCHAR (128) NULL,
    [ContactName]                            VARCHAR (128) NULL,
    [ContactPhoneNo]                         VARCHAR (128) NULL,
    [ContactEmail]                           VARCHAR (MAX) NULL,
    [Comments]                               VARCHAR (MAX) NULL,
    [ContactFaxNo]                           VARCHAR (128) NULL,
    [RegionId]                               INT           NULL,
    [ContactName2]                           VARCHAR (128) NULL,
    [ContactPhoneNo2]                        VARCHAR (128) NULL,
    [ContactEmail2]                          VARCHAR (MAX) NULL,
    [ContactName3]                           VARCHAR (128) NULL,
    [ContactPhoneNo3]                        VARCHAR (128) NULL,
    [ContactEmail3]                          VARCHAR (MAX) NULL,
    [MasterLicenseNo]                        VARCHAR (128) NULL,
    [MasterLicenseNoExpiryDate]              DATETIME      NULL,
    [PublicLiabilityInsurer]                 VARCHAR (128) NULL,
    [PublicLiabilityPolicyNo]                VARCHAR (128) NULL,
    [PublicLiabilityExpiryDate]              DATETIME      NULL,
    [WorkersCompensationInsurer]             VARCHAR (128) NULL,
    [WorkersCompensationPolicyNo]            VARCHAR (128) NULL,
    [WorkersCompensationExpiryDate]          DATETIME      NULL,
    [MasterLicenseNoExpiryEmailSentDate]     DATETIME      NULL,
    [PublicLiabilityExpiryEmailSentDate]     DATETIME      NULL,
    [WorkersCompensationExpiryEmailSentDate] DATETIME      NULL,
    [StatuatoryDeclarationEmailSentDate]     DATETIME      NULL,
    [ABN]                                    VARCHAR (11)  NULL,
    [AttachmentDescription]                  VARCHAR (MAX) NULL,
    [SubcontractorPIN]                       VARCHAR (MAX) NULL,
    [SCAPPAcceptJobOption]                   INT           NULL,
    [IsParking]                              INT           NULL,
    [StaffPrefix]                            VARCHAR (128) NULL,
    [StaffIdLength]                          INT           NULL,
    [RAPID2ProfileParameterId]               INT           NULL,
    [AutomaticallyEmailReminders]            BIT           NULL,
    [DefaultRosteringLoginID]                VARCHAR (128) NULL,
    [OperatingStateId]                       INT           NULL,
    [ChargeRateId]                           INT           NULL,
    PRIMARY KEY CLUSTERED ([SubContractorId] ASC)
);

