CREATE TABLE [ods].[STG_WS_PERMPATROL] (
    [PermanentPatrolId]                   INT             NOT NULL,
    [Status]                              BIT             NULL,
    [StatusLastChangedDateTime]           DATETIME        NULL,
    [PatrolName]                          VARCHAR (128)   NULL,
    [ClientId]                            INT             NULL,
    [MondayStartTime]                     DATETIME        NULL,
    [MondayEndTime]                       DATETIME        NULL,
    [MondayCount]                         INT             NULL,
    [MondayVisitCharge]                   DECIMAL (10, 2) NULL,
    [MondayTimeAllowed]                   INT             NULL,
    [MondayRatePerMinute]                 DECIMAL (10, 2) NULL,
    [TuesdayStartTime]                    DATETIME        NULL,
    [TuesdayEndTime]                      DATETIME        NULL,
    [TuesdayCount]                        INT             NULL,
    [TuesdayVisitCharge]                  DECIMAL (10, 2) NULL,
    [TuesdayTimeAllowed]                  INT             NULL,
    [TuesdayRatePerMinute]                DECIMAL (10, 2) NULL,
    [WednesdayStartTime]                  DATETIME        NULL,
    [WednesdayEndTime]                    DATETIME        NULL,
    [WednesdayCount]                      INT             NULL,
    [WednesdayVisitCharge]                DECIMAL (10, 2) NULL,
    [WednesdayTimeAllowed]                INT             NULL,
    [WednesdayRatePerMinute]              DECIMAL (10, 2) NULL,
    [ThursdayStartTime]                   DATETIME        NULL,
    [ThursdayEndTime]                     DATETIME        NULL,
    [ThursdayCount]                       INT             NULL,
    [ThursdayVisitCharge]                 DECIMAL (10, 2) NULL,
    [ThursdayTimeAllowed]                 INT             NULL,
    [ThursdayRatePerMinute]               DECIMAL (10, 2) NULL,
    [FridayStartTime]                     DATETIME        NULL,
    [FridayEndTime]                       DATETIME        NULL,
    [FridayCount]                         INT             NULL,
    [FridayVisitCharge]                   DECIMAL (10, 2) NULL,
    [FridayTimeAllowed]                   INT             NULL,
    [FridayRatePerMinute]                 DECIMAL (10, 2) NULL,
    [SaturdayStartTime]                   DATETIME        NULL,
    [SaturdayEndTime]                     DATETIME        NULL,
    [SaturdayCount]                       INT             NULL,
    [SaturdayVisitCharge]                 DECIMAL (10, 2) NULL,
    [SaturdayTimeAllowed]                 INT             NULL,
    [SaturdayRatePerMinute]               DECIMAL (10, 2) NULL,
    [SundayStartTime]                     DATETIME        NULL,
    [SundayEndTime]                       DATETIME        NULL,
    [SundayCount]                         INT             NULL,
    [SundayVisitCharge]                   DECIMAL (10, 2) NULL,
    [SundayTimeAllowed]                   INT             NULL,
    [SundayRatePerMinute]                 DECIMAL (10, 2) NULL,
    [PublicHolidayStartTime]              DATETIME        NULL,
    [PublicHolidayEndTime]                DATETIME        NULL,
    [PublicHolidayCount]                  INT             NULL,
    [PublicHolidayVisitCharge]            DECIMAL (10, 2) NULL,
    [PublicHolidayTimeAllowed]            INT             NULL,
    [PublicHolidayRatePerMinute]          DECIMAL (10, 2) NULL,
    [Comments]                            VARCHAR (MAX)   NULL,
    [RunChainNo]                          VARCHAR (128)   NULL,
    [DespatchZoneId]                      INT             NULL,
    [LastDespatchDate]                    DATETIME        NULL,
    [LeaveTicket]                         BIT             NULL,
    [SubContractorId]                     INT             NULL,
    [PatrolServiceTypeId]                 INT             NULL,
    [FixedFeeInvoicing]                   BIT             NULL,
    [FixedFeeAmountExGST]                 DECIMAL (10, 2) NULL,
    [LastFixedFeeInvoiceDate]             DATETIME        NULL,
    [InvoiceRefText]                      VARCHAR (MAX)   NULL,
    [PatrolType]                          INT             NULL,
    [PatrolStartDate]                     DATETIME        NULL,
    [PatrolEndDate]                       DATETIME        NULL,
    [PONumber]                            VARCHAR (128)   NULL,
    [NeverCharge]                         BIT             NULL,
    [StatusLastChangedUserId]             INT             NULL,
    [PublicHolidaySurchargeFixedFeeExGST] DECIMAL (10, 2) NULL,
    [FeePerMinute]                        BIT             NULL,
    [FeePerMinuteRate]                    DECIMAL (10, 2) NULL,
    [PatrolSLAApplied]                    INT             NULL,
    PRIMARY KEY CLUSTERED ([PermanentPatrolId] ASC)
);

