CREATE TABLE [ods].[STG_WS_ALARMDOCKET] (
    [AlarmDocketId]                     INT             NOT NULL,
    [EntryClerkUserId]                  INT             NULL,
    [EntryDateTimeStart]                DATETIME        NULL,
    [EntryDateTimeEnd]                  DATETIME        NULL,
    [IsComplete]                        BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_IsComplete] DEFAULT ((0)) NULL,
    [Status]                            BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_Status] DEFAULT ((0)) NULL,
    [AlarmDocketNo]                     VARCHAR (16)    NULL,
    [KDTNo]                             VARCHAR (16)    NULL,
    [ClientId]                          INT             NULL,
    [HostTransactionId]                 INT             NULL,
    [MonitoringStationId]               INT             NULL,
    [ExportDate]                        DATETIME        NULL,
    [BillDirect]                        BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_BillDirect] DEFAULT ((0)) NULL,
    [CallExceptionId]                   INT             NULL,
    [AlarmResponseDateTime]             DATETIME        NULL,
    [Shift]                             VARCHAR (8)     NULL,
    [AlarmOnSiteDateTime]               DATETIME        NULL,
    [AlarmOffSiteDateTime]              DATETIME        NULL,
    [MobileCS]                          VARCHAR (16)    NULL,
    [PatrolOfficerEmployeeId]           INT             NULL,
    [SubContractorId]                   INT             NULL,
    [Zone]                              VARCHAR (16)    NULL,
    [BaseAmount]                        DECIMAL (10, 2) NULL,
    [AdditionalAmount]                  DECIMAL (10, 2) NULL,
    [DaySurcharge]                      DECIMAL (10, 2) NULL,
    [GSTAmount]                         DECIMAL (10, 2) NULL,
    [ChargeTotal]                       DECIMAL (10, 2) NULL,
    [PurchaseOrderNo]                   VARCHAR (128)   NULL,
    [Comments]                          VARCHAR (MAX)   NULL,
    [FollowupInfo]                      VARCHAR (MAX)   NULL,
    [SiteVisualAppraisalId]             INT             NULL,
    [SystemStatusOnDepartureId]         INT             NULL,
    [ClientContacted]                   BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ClientContacted] DEFAULT ((0)) NULL,
    [ClientContactName]                 VARCHAR (MAX)   NULL,
    [GlazierContacted]                  BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_GlazierContacted] DEFAULT ((0)) NULL,
    [PoliceContacted]                   BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_PoliceContacted] DEFAULT ((0)) NULL,
    [PoliceDetails]                     VARCHAR (MAX)   NULL,
    [AdditionalClientInfo]              VARCHAR (MAX)   NULL,
    [AttachmentDescription]             VARCHAR (MAX)   NULL,
    [SystemArmed]                       INT             NULL,
    [ZoneSector]                        VARCHAR (20)    NULL,
    [TimeToRespondInMinutes]            INT             NULL,
    [TimeOnSiteInMinutes]               INT             NULL,
    [ExtraTimeOnSiteInMinutes]          INT             NULL,
    [OverResponseTimeInMinutes]         INT             NULL,
    [RegionId]                          INT             NULL,
    [CallException2Id]                  INT             NULL,
    [DespatchZone1]                     INT             NULL,
    [DespatchZone2]                     INT             NULL,
    [AckDateTime]                       DATETIME        NULL,
    [JobText]                           VARCHAR (MAX)   NULL,
    [SpecialInstructions]               VARCHAR (MAX)   NULL,
    [Hazards]                           VARCHAR (MAX)   NULL,
    [OtherDocketType]                   INT             NULL,
    [TempClientSite]                    VARCHAR (128)   NULL,
    [TempClientAddress1]                VARCHAR (128)   NULL,
    [TempClientAddress2]                VARCHAR (128)   NULL,
    [TempClientSuburbId]                INT             NULL,
    [NotificationEmailSentDateTime]     DATETIME        NULL,
    [OnsiteVehicleStoppedDateTime]      DATETIME        NULL,
    [OnsiteLat]                         VARCHAR (64)    NULL,
    [OnsiteLong]                        VARCHAR (64)    NULL,
    [OnsiteDistanceFromSite]            VARCHAR (64)    NULL,
    [WSCIAudit]                         VARCHAR (MAX)   NULL,
    [MonitoringStationDespatcherName]   VARCHAR (128)   NULL,
    [PatrolOfficerName]                 VARCHAR (128)   NULL,
    [ServiceTypeId]                     INT             NULL,
    [AddressWhenOnsited]                VARCHAR (MAX)   NULL,
    [DespatchTypeId]                    INT             NULL,
    [AlarmType]                         VARCHAR (128)   NULL,
    [ChargeTotalIncGST]                 DECIMAL (10, 2) NULL,
    [ChargeTotalExGST]                  DECIMAL (10, 2) NULL,
    [GSTApplicableId]                   INT             NULL,
    [Exported]                          BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_Exported] DEFAULT ((0)) NULL,
    [DespatchEntryDateTime]             DATETIME        NULL,
    [DespatchSnapShot]                  VARCHAR (MAX)   NULL,
    [TravelChargeAmount]                DECIMAL (10, 2) NULL,
    [ExtendedJSONRequest]               VARCHAR (MAX)   NULL,
    [ExtendedJSONResponse]              VARCHAR (MAX)   NULL,
    [ComplianceORTAltered]              BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceORTAltered] DEFAULT ((0)) NULL,
    [ComplianceResponseDTSAltered]      BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceResponseDTSAltered] DEFAULT ((0)) NULL,
    [ComplianceOnsiteDTSAltered]        BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceOnsiteDTSAltered] DEFAULT ((0)) NULL,
    [ComplianceOffsiteDTSAltered]       BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceOffsiteDTSAltered] DEFAULT ((0)) NULL,
    [ComplianceChargeRateAltered]       BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceChargeRateAltered] DEFAULT ((0)) NULL,
    [ComplianceChargeRateOverridden]    BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceChargeRateOverridden] DEFAULT ((0)) NULL,
    [ComplianceNoChargeApplied]         BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceNoChargeApplied] DEFAULT ((0)) NULL,
    [ComplianceORTExceptionAltered]     BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceORTExceptionAltered] DEFAULT ((0)) NULL,
    [ComplianceAdditionalTimeExAltered] BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_ComplianceAdditionalTimeExAltered] DEFAULT ((0)) NULL,
    [ComplianceOutcome]                 INT             NULL,
    [KeySetId]                          INT             NULL,
    [HadKeyIssue]                       BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_HadKeyIssue] DEFAULT ((0)) NULL,
    [KeyIssue]                          INT             NULL,
    [ETLRunID]                          INT             NULL,
    [Exemption]                         BIT             CONSTRAINT [DF_STG_WS_ALARMDOCKET_Exemption] DEFAULT ((0)) NULL,
    [HitMiss]                           INT             NULL,
    PRIMARY KEY CLUSTERED ([AlarmDocketId] ASC)
);

