CREATE TABLE [ods].[STG_WS_ZONE] (
    [DespatchZoneId]             INT             NOT NULL,
    [Status]                     BIT             NULL,
    [ZoneIDcode]                 VARCHAR (8)     NULL,
    [Name]                       VARCHAR (128)   NULL,
    [LabourCostPerHour]          DECIMAL (10, 2) NULL,
    [RegionId]                   INT             NULL,
    [StateId]                    INT             NULL,
    [LastPingDateTime]           DATETIME        NULL,
    [OnlineStatus]               INT             NULL,
    [WorkStatus]                 INT             NULL,
    [ETAtoJob]                   INT             NULL,
    [EstFreeTime]                INT             NULL,
    [OtherInfo]                  VARCHAR (MAX)   NULL,
    [ShiftStartTime]             DATETIME        NULL,
    [ShiftEndTime]               DATETIME        NULL,
    [DespatchSMS]                VARCHAR (128)   NULL,
    [DespatchEmail]              VARCHAR (MAX)   NULL,
    [CurrentVehicleRego]         VARCHAR (128)   NULL,
    [DailyClearDespatchSMS]      BIT             NULL,
    [ServiceProvider]            INT             NULL,
    [ServiceProviderDefaultUser] VARCHAR (128)   NULL,
    [DespatchZoneDepotId]        INT             NULL,
    [FleetCostPerHour]           DECIMAL (10, 2) NULL,
    [PermanentDespatchSMS]       VARCHAR (128)   NULL,
    [IncludeInReporting]         BIT             NULL,
    [OtherCostPerHour]           DECIMAL (10, 2) NULL,
    [SubcontractorDespatchZone]  BIT             NULL,
    [KeyModuleOption]            INT             NULL,
    [LastKnownLat]               FLOAT (53)      NULL,
    [LastKnownLong]              FLOAT (53)      NULL,
    [LastKnownAddress]           VARCHAR (MAX)   NULL,
    [WelfareCheckOnJobPeriod]    INT             NULL,
    [WelfareCheckOffJobPeriod]   INT             NULL,
    [WelfareCheckGUID]           VARCHAR (64)    NULL,
    PRIMARY KEY CLUSTERED ([DespatchZoneId] ASC)
);

