CREATE TABLE [ods].[STG_WS_BUREAU] (
    [BureauId]                              INT             NOT NULL,
    [EntryClerkUserId]                      INT             NULL,
    [EntryDateTimeStart]                    DATETIME        NULL,
    [EntryDateTimeEnd]                      DATETIME        NULL,
    [IsComplete]                            BIT             NULL,
    [Status]                                BIT             NULL,
    [DebtorCode]                            VARCHAR (64)    NULL,
    [Name]                                  VARCHAR (MAX)   NULL,
    [BureauIDCode]                          VARCHAR (128)   NULL,
    [AgentPrefix]                           VARCHAR (16)    NULL,
    [BulkBill]                              BIT             NULL,
    [DirectBill]                            BIT             NULL,
    [ChargeRateId]                          INT             NULL,
    [PhoneNo]                               VARCHAR (128)   NULL,
    [FaxNo]                                 VARCHAR (128)   NULL,
    [Comments]                              VARCHAR (MAX)   NULL,
    [LastAlarmResponseDate]                 DATETIME        NULL,
    [LastContactDate]                       DATETIME        NULL,
    [RegionId]                              INT             NULL,
    [NeverOverrideClientChargeRate]         BIT             NULL,
    [SendBureauAlarmDocketNotification]     BIT             NULL,
    [SendClientAlarmDocketNotification]     BIT             NULL,
    [PermanentPatrolRatePerMinute]          DECIMAL (10, 2) NULL,
    [CasualPatrolRateExGST]                 DECIMAL (10, 2) NULL,
    [AlarmResponseBillingCycle]             INT             NULL,
    [AlarmResponseLastBillingCycleDate]     DATETIME        NULL,
    [RFCBillingCycle]                       INT             NULL,
    [RFCLastBillingCycleDate]               DATETIME        NULL,
    [PatrolFixedFeeBillingCycle]            INT             NULL,
    [PatrolFixedFeeLastBillingCycleDate]    DATETIME        NULL,
    [PatrolFeePerVisitBillingCycle]         INT             NULL,
    [PatrolFeePerVisitLastBillingCycleDate] DATETIME        NULL,
    [CostCentre]                            VARCHAR (64)    NULL,
    [GLcode]                                VARCHAR (64)    NULL,
    [CostCentreCasualPatrol]                VARCHAR (64)    NULL,
    [GLcodeCasualPatrol]                    VARCHAR (64)    NULL,
    [CostCentrePermPatrol]                  VARCHAR (64)    NULL,
    [GLcodePermPatrol]                      VARCHAR (64)    NULL,
    [GroupInvoicesBy]                       INT             NULL,
    [PermanentPurchaseOrderNo]              VARCHAR (128)   NULL,
    [CostCentreServices]                    VARCHAR (64)    NULL,
    [CostCentreMonitoring]                  VARCHAR (64)    NULL,
    [CostCentreMaintenance]                 VARCHAR (64)    NULL,
    [GLcodeServices]                        VARCHAR (64)    NULL,
    [GLcodeMonitoring]                      VARCHAR (64)    NULL,
    [GLcodeMaintenance]                     VARCHAR (64)    NULL,
    [CasualPatrolRateType]                  INT             NULL,
    [IsSuspended]                           BIT             NULL,
    [SuspendedDate]                         DATETIME        NULL,
    [SuspendedReason]                       VARCHAR (MAX)   NULL,
    [SuspendedUserId]                       INT             NULL,
    [ClientServiceManagerUserId]            INT             NULL,
    [OriginalSourceID]                      INT             NULL,
    [OriginalSourceDebtorCode]              VARCHAR (64)    NULL,
    [OriginalSourceCostCentre]              VARCHAR (64)    NULL,
    [ABN]                                   VARCHAR (11)    NULL,
    [OverrideABNValidation]                 BIT             NULL,
    [SpecialInstructions]                   VARCHAR (MAX)   NULL,
    [AddToClientSpecialInstructions]        INT             NULL,
    PRIMARY KEY CLUSTERED ([BureauId] ASC)
);

