






CREATE VIEW [eda].[ETL_EVENT_RECENT]
AS

SELECT				e.*, b.VARIABLE_VALUE EXTRACT_BRANCH, f.VARIABLE_VALUE EXTRACT_FROM, t.VARIABLE_VALUE EXTRACT_TO
FROM				eda.ETL_EVENT e
INNER JOIN			(SELECT EVENT_ID, VARIABLE_VALUE FROM eda.ETL_EVENT_VARIABLES WHERE VARIABLE_CODE = 'EXTRACT_BRANCH') b on e.EVENT_ID = b.EVENT_ID
INNER JOIN			(SELECT EVENT_ID, VARIABLE_VALUE FROM eda.ETL_EVENT_VARIABLES WHERE VARIABLE_CODE = 'EXTRACT_FROM') f on e.EVENT_ID = f.EVENT_ID
INNER JOIN			(SELECT EVENT_ID, VARIABLE_VALUE FROM eda.ETL_EVENT_VARIABLES WHERE VARIABLE_CODE = 'EXTRACT_TO') t on e.EVENT_ID = t.EVENT_ID
WHERE				DATEDIFF(DD,e.EVENT_DATE_CREATE,sysdatetime()) <= 3

