CREATE TABLE [eda].[ETL_EVENT] (
    [EVENT_ID]           INT            IDENTITY (1, 1) NOT NULL,
    [ETL_REF]            INT            NOT NULL,
    [ETL_RUN_CODE]       INT            NULL,
    [EVENT_STATUS]       VARCHAR (50)   NOT NULL,
    [EVENT_DATE_CREATE]  DATETIME       NOT NULL,
    [EVENT_SOURCE]       VARCHAR (100)  NOT NULL,
    [EVENT_INPUT]        VARCHAR (255)  NOT NULL,
    [EVENT_OUTPUT]       VARCHAR (255)  NOT NULL,
    [EVENT_USER_EMAIL]   VARCHAR (1000) NOT NULL,
    [EVENT_KICKOFF_DATE] DATETIME       NULL,
    [EVENT_DATE_START]   DATETIME       NULL,
    [EVENT_DATE_END]     DATETIME       NULL,
    [EVENT_COMMENT]      VARCHAR (4000) NULL,
    [DATE_LAST_MODIFIED] DATETIME       NOT NULL,
    [EVENT_EXECUTION_ID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([EVENT_ID] ASC)
);

