CREATE TABLE [eda].[ETL_EVENT_VARIABLES] (
    [EVENT_ID]           INT           NOT NULL,
    [VARIABLE_CODE]      VARCHAR (50)  NOT NULL,
    [DATA_TYPE]          VARCHAR (50)  NOT NULL,
    [VARIABLE_DESC]      VARCHAR (255) NOT NULL,
    [VARIABLE_VALUE]     VARCHAR (255) NOT NULL,
    [DATE_LAST_MODIFIED] DATETIME      NOT NULL,
    CONSTRAINT [PK_CTL_JOB_CONFIG_VARIABLES] PRIMARY KEY CLUSTERED ([EVENT_ID] ASC, [VARIABLE_CODE] ASC)
);

