CREATE TABLE [eda].[EXT_IT_ROSTERFULL] (
    [eventId]            INT           NULL,
    [assignmentId]       BIGINT        NULL,
    [assignmentRow]      INT           NULL,
    [inTimeId]           VARCHAR (50)  NULL,
    [workGroup]          VARCHAR (100) NULL,
    [empDisplayName]     VARCHAR (150) NULL,
    [assignmentDate]     DATE          NULL,
    [branchRef]          VARCHAR (50)  NULL,
    [branchName]         VARCHAR (200) NULL,
    [origin]             VARCHAR (25)  NULL,
    [startTime]          DATETIME      NULL,
    [endTime]            DATETIME      NULL,
    [customerName]       VARCHAR (200) NULL,
    [debtorCode]         VARCHAR (50)  NULL,
    [locationName]       VARCHAR (200) NULL,
    [locShortName]       VARCHAR (50)  NULL,
    [locBillType]        VARCHAR (200) NULL,
    [subLocationName]    VARCHAR (200) NULL,
    [jobCode]            VARCHAR (50)  NULL,
    [locationRef]        VARCHAR (20)  NULL,
    [locationCode]       VARCHAR (20)  NULL,
    [subLocationRef]     VARCHAR (20)  NULL,
    [sublocationCode]    VARCHAR (20)  NULL,
    [activityCode]       VARCHAR (50)  NULL,
    [activityName]       VARCHAR (50)  NULL,
    [precActPay]         VARCHAR (2)   NULL,
    [gtActPay]           VARCHAR (10)  NULL,
    [gtActActivity]      VARCHAR (10)  NULL,
    [narration]          VARCHAR (MAX) NULL,
    [lengthHours]        FLOAT (53)    NULL,
    [regularHours]       FLOAT (53)    NULL,
    [leaveHours]         FLOAT (53)    NULL,
    [precLeavePay]       VARCHAR (2)   NULL,
    [gtLeaveActivity]    VARCHAR (10)  NULL,
    [gtLeavePay]         VARCHAR (10)  NULL,
    [wgOvertimeHours]    FLOAT (53)    NULL,
    [multHours]          FLOAT (53)    NULL,
    [multCode]           VARCHAR (50)  NULL,
    [multPremium]        FLOAT (53)    NULL,
    [addHRRate]          FLOAT (53)    NULL,
    [rateMultipler]      FLOAT (53)    NULL,
    [precHMPay]          VARCHAR (2)   NULL,
    [gtHMPay]            VARCHAR (10)  NULL,
    [precHMAll]          VARCHAR (2)   NULL,
    [gtHMAll]            VARCHAR (10)  NULL,
    [gtHMActivity]       VARCHAR (10)  NULL,
    [unpaidBreakHours]   FLOAT (53)    NULL,
    [onCallHours]        FLOAT (53)    NULL,
    [regMultVar]         FLOAT (53)    NULL,
    [excludedLeaveHours] FLOAT (53)    NULL,
    [excludedLeaveCode]  VARCHAR (100) NULL,
    [phWorkedHours]      FLOAT (53)    NULL,
    [precPHPay]          VARCHAR (2)   NULL,
    [gtPHPay]            VARCHAR (10)  NULL,
    [gtPHActivity]       VARCHAR (10)  NULL,
    [addLIEUCredit]      BIT           NULL,
    [phId]               INT           NULL,
    [dateLastModified]   DATETIME      NULL,
    [qaPass]             BIT           NULL,
    [qaComment]          VARCHAR (250) NULL,
    [extracted]          BIT           NULL,
    [precedaId]          VARCHAR (6)   NULL,
    [jobOverride]        VARCHAR (50)  NULL,
    [isTemplate]         BIT           NULL
);

