CREATE TABLE [eda].[EXT_DEP_FULL] (
    [Id]               INT           NULL,
    [AgreementId]      INT           NULL,
    [EmployeeId]       INT           NULL,
    [payrollId]        VARCHAR (100) NULL,
    [LeaveRuleId]      INT           NULL,
    [LeaveLineId]      INT           NULL,
    [PayCycleId]       INT           NULL,
    [AreaId]           INT           NULL,
    [displayName]      VARCHAR (100) NULL,
    [firstName]        VARCHAR (50)  NULL,
    [lastName]         VARCHAR (50)  NULL,
    [employer]         VARCHAR (100) NULL,
    [payCentre]        VARCHAR (255) NULL,
    [payPeriod]        VARCHAR (50)  NULL,
    [exportCode]       VARCHAR (100) NULL,
    [CostCentre]       VARCHAR (100) NULL,
    [AreaProduct]      VARCHAR (50)  NULL,
    [AreaRateName]     VARCHAR (50)  NULL,
    [areaName]         VARCHAR (255) NULL,
    [locationName]     VARCHAR (255) NULL,
    [branchName]       VARCHAR (255) NULL,
    [timesheetStart]   DATETIME      NULL,
    [timesheetEnd]     DATETIME      NULL,
    [timesheetHours]   FLOAT (53)    NULL,
    [timesheetCost]    FLOAT (53)    NULL,
    [sourceType]       VARCHAR (10)  NULL,
    [sourceStart]      DATETIME      NULL,
    [sourceEnd]        DATETIME      NULL,
    [sourceHours]      FLOAT (53)    NULL,
    [sourceCost]       FLOAT (53)    NULL,
    [InProgress]       BIT           NULL,
    [RealTime]         BIT           NULL,
    [AutoProcessed]    BIT           NULL,
    [PayApproved]      BIT           NULL,
    [TimeApproved]     BIT           NULL,
    [AutoPayApproved]  BIT           NULL,
    [AutoTimeApproved] BIT           NULL,
    [Exported]         BIT           NULL,
    [Invoiced]         BIT           NULL,
    [emsminutes]       FLOAT (53)    NULL,
    [ncrminutes]       FLOAT (53)    NULL,
    [ponumber]         VARCHAR (255) NULL,
    [ritm]             VARCHAR (255) NULL,
    [sourcePO]         VARCHAR (255) NULL,
    [sorceRITM]        VARCHAR (255) NULL,
    [lineCost]         FLOAT (53)    NULL,
    [payActivityCode]  VARCHAR (50)  NULL,
    [payTitle]         VARCHAR (100) NULL,
    [lineHours]        FLOAT (53)    NULL,
    [emsHours]         FLOAT (53)    NULL,
    [ncrHours]         FLOAT (53)    NULL,
    [Overridden]       BIT           NULL,
    [OverrideComment]  VARCHAR (100) NULL,
    [BaseRate]         FLOAT (53)    NULL,
    [EMSRate]          FLOAT (53)    NULL,
    [SiteRate]         FLOAT (53)    NULL,
    [TierRate]         FLOAT (53)    NULL,
    [TierProductCode]  VARCHAR (50)  NULL,
    [TierRateName]     VARCHAR (50)  NULL,
    [phHours]          FLOAT (53)    NULL,
    [altCredit]        BIT           NULL,
    [phRef]            INT           NULL,
    [MDEventId]        BIGINT        NULL
);

