CREATE TABLE [eda].[STG_DEPTIMESHEET] (
    [Id]               INT           NULL,
    [AgreementId]      INT           NULL,
    [EmployeeId]       INT           NULL,
    [LeaveRuleId]      INT           NULL,
    [LeaveLineId]      INT           NULL,
    [RosterId]         INT           NULL,
    [PayCycleId]       INT           NULL,
    [AreaId]           INT           NULL,
    [LocationId]       INT           NULL,
    [AreaName]         VARCHAR (100) NULL,
    [JobCode]          VARCHAR (100) NULL,
    [timesheetStart]   DATETIME      NULL,
    [timesheetEnd]     DATETIME      NULL,
    [timesheetHours]   FLOAT (53)    NULL,
    [timesheetCost]    FLOAT (53)    NULL,
    [sourceType]       VARCHAR (10)  NULL,
    [sourceStart]      DATETIME      NULL,
    [sourceEnd]        DATETIME      NULL,
    [sourceHours]      FLOAT (53)    NULL,
    [sourceCost]       FLOAT (53)    NULL,
    [InProgress]       BIT           NULL,
    [RealTime]         BIT           NULL,
    [AutoProcessed]    BIT           NULL,
    [PayApproved]      BIT           NULL,
    [TimeApproved]     BIT           NULL,
    [AutoPayApproved]  BIT           NULL,
    [AutoTimeApproved] BIT           NULL,
    [Exported]         BIT           NULL,
    [Paid]             BIT           NULL,
    [Invoiced]         BIT           NULL,
    [emsminutes]       FLOAT (53)    NULL,
    [ncrminutes]       FLOAT (53)    NULL,
    [ponumber]         VARCHAR (255) NULL,
    [ritm]             VARCHAR (255) NULL
);

