CREATE TABLE [agg].[DIM_Staff_Full] (
    [homeBranch]          INT             NULL,
    [StaffID]             BIGINT          NULL,
    [IntRef]              VARCHAR (50)    NULL,
    [FirstName]           VARCHAR (50)    NULL,
    [LastName]            VARCHAR (50)    NULL,
    [MiddleName]          VARCHAR (50)    NULL,
    [DOB]                 DATE            NULL,
    [Status]              VARCHAR (50)    NULL,
    [Type]                VARCHAR (50)    NULL,
    [employeeId]          NVARCHAR (255)  NULL,
    [coa]                 NVARCHAR (255)  NULL,
    [hireDate]            DATE            NULL,
    [terminationDate]     DATE            NULL,
    [CELL_PHONE]          VARCHAR (MAX)   NULL,
    [SMS]                 VARCHAR (MAX)   NULL,
    [HOME_PHONE]          VARCHAR (MAX)   NULL,
    [WORK_PHONE]          VARCHAR (MAX)   NULL,
    [FAX]                 VARCHAR (MAX)   NULL,
    [PAGER]               VARCHAR (MAX)   NULL,
    [OTHER]               VARCHAR (MAX)   NULL,
    [EMAIL]               VARCHAR (MAX)   NULL,
    [EMERGENCY]           VARCHAR (MAX)   NULL,
    [subcontractorGroup]  VARCHAR (30)    NULL,
    [gtId]                VARCHAR (34)    NULL,
    [empid]               VARCHAR (50)    NULL,
    [fullname]            NVARCHAR (63)   NULL,
    [gender]              VARCHAR (31)    NULL,
    [homePhone]           VARCHAR (51)    NULL,
    [businessPhone]       VARCHAR (51)    NULL,
    [mobile]              VARCHAR (51)    NULL,
    [isInactive]          BIT             NULL,
    [startDate]           DATE            NULL,
    [nextAnniversaryDate] DATE            NULL,
    [payGroup]            VARCHAR (31)    NULL,
    [branchCode]          VARCHAR (7)     NULL,
    [defaultPayCode]      VARCHAR (9)     NULL,
    [baseHourRate]        NUMERIC (14, 4) NULL,
    [hrBasis]             VARCHAR (61)    NULL,
    [hrType]              VARCHAR (61)    NULL
);

