CREATE TABLE [agg].[FCT_WS_Patrols] (
    [RegionId]                   INT             NULL,
    [ClientId]                   INT             NULL,
    [AckDateTime]                DATETIME        NULL,
    [OnSiteDateTime]             DATETIME        NULL,
    [OffSiteDateTime]            DATETIME        NULL,
    [AlarmDocketId]              INT             NULL,
    [DespatchTypeId]             INT             NULL,
    [MonitoringStationId]        INT             NULL,
    [PermanentPatrolId]          INT             NULL,
    [OnsiteLat]                  VARCHAR (64)    NULL,
    [OnsiteLong]                 VARCHAR (64)    NULL,
    [OnsiteDistanceFromSite]     VARCHAR (64)    NULL,
    [Code]                       VARCHAR (64)    NULL,
    [Description]                VARCHAR (128)   NULL,
    [joboid]                     VARCHAR (128)   NULL,
    [DespatchId]                 INT             NULL,
    [TotalCount]                 INT             NULL,
    [MissedCount]                INT             NULL,
    [Patrol Client Value]        NUMERIC (10, 2) NULL,
    [pcBusNo]                    VARCHAR (50)    NULL,
    [pcBranchNo]                 VARCHAR (50)    NULL,
    [DespatchDateTime]           DATETIME        NULL,
    [DespatchZoneId]             INT             NULL,
    [PermanentPatrolCompletedId] INT             NULL,
    [Hazards]                    VARCHAR (MAX)   NULL,
    [SpecialInstructions]        VARCHAR (MAX)   NULL,
    [DespatchZone1Id]            INT             NULL,
    [DespatchZone2Id]            INT             NULL,
    [PatrolOfficerEmployee1Id]   INT             NULL,
    [JobText]                    VARCHAR (MAX)   NULL,
    [Missed Value]               NUMERIC (21, 2) NULL,
    [MIssed Patrols %]           NUMERIC (11, 1) NULL,
    [DATEFILTERPERIOD]           BIT             NULL,
    [DATEFILTERPERIOD2]          BIT             NULL,
    [TimeOnSiteInMinutes]        INT             NULL,
    [pcName]                     VARCHAR (100)   NULL,
    [Zone Name]                  VARCHAR (128)   NULL
);

