CREATE TABLE [dw].[BKP_DIM_DATE2] (
    [SK_DIM_DATE]           BIGINT        NOT NULL,
    [PK_DW_Source_system]   VARCHAR (50)  NULL,
    [PK_Date]               SMALLDATETIME NOT NULL,
    [FK_DIM_GT_PERIOD]      INT           NULL,
    [T_Day_Of_Month_No]     INT           NULL,
    [T_Day_Of_Year_No]      INT           NULL,
    [T_Week_No]             INT           NULL,
    [T_Day_Of_Week_No]      INT           NULL,
    [T_Day_Of_Week]         VARCHAR (20)  NULL,
    [T_Month_No]            INT           NULL,
    [T_Month]               VARCHAR (20)  NULL,
    [T_Month_Short]         VARCHAR (3)   NULL,
    [T_Year]                INT           NULL,
    [T_Start_Of_Month_Date] SMALLDATETIME NULL,
    [T_End_Of_Month_Date]   SMALLDATETIME NULL,
    [T_Start_Of_Week_date]  SMALLDATETIME NULL,
    [F_Day_Of_Year_No]      INT           NULL,
    [F_Week_No]             INT           NULL,
    [F_Month_No]            INT           NULL,
    [F_Quarter]             INT           NULL,
    [F_Year]                INT           NULL,
    [MD_DATE_CREATED]       DATE          NULL,
    [MD_DATE_MODIFIED]      DATE          NULL,
    [MD_LOGICAL_DELETE]     SMALLINT      NULL,
    [MD_JOB_CODE]           INT           NULL,
    [MD_RUN_CODE]           BIGINT        NULL,
    [MD_PACK_NAME]          VARCHAR (70)  NULL
);

