CREATE TABLE [dw].[DIM_GHS_USERS_ORGANISATIONS] (
    [SK_USERS_ORG]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [P_USERS_ORG_ID]          BIGINT        NOT NULL,
    [FK_SK_DIM_USERS]         BIGINT        NULL,
    [FK_SK_DIM_ORGANISATIONS] BIGINT        NULL,
    [MD_DATE_CREATED]         DATETIME      NULL,
    [MD_DATE_MODIFIED]        DATETIME      NULL,
    [MD_JOB_CODE]             INT           NULL,
    [MD_RUN_CODE]             BIGINT        NULL,
    [MD_PACK_NAME]            VARCHAR (70)  NULL,
    [MD_MODIFIED_USER]        VARCHAR (100) NULL,
    [MD_LOGICAL_DELETE]       SMALLINT      NULL,
    PRIMARY KEY CLUSTERED ([SK_USERS_ORG] ASC),
    CONSTRAINT [FK_DIM_GHS_USERS_ORG_DIM_GHS_ORGS] FOREIGN KEY ([FK_SK_DIM_ORGANISATIONS]) REFERENCES [dw].[DIM_GHS_ORGANISATIONS] ([SK_DIM_ORGANISATIONS]),
    CONSTRAINT [FK_DIM_GHS_USERS_ORG_DIM_GHS_USERS] FOREIGN KEY ([FK_SK_DIM_USERS]) REFERENCES [dw].[DIM_GHS_USERS] ([SK_DIM_USERS])
);

