CREATE TABLE [dw].[DIM_LH_ROLE] (
    [SK_DIM_LH_ROLE]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_ROLE_ID]          VARCHAR (255) NULL,
    [P_ROLE_NAME]         VARCHAR (255) NULL,
    [P_ROLE_CREATED_AT]   DATETIME      NULL,
    [P_ROLE_UPDATED_AT]   DATETIME      NULL,
    [P_REVISION_NUMBER]   BIGINT        NULL,
    [P_DOCUMENT_DATE]     DATETIME      NULL,
    [MD_FILENAME]         VARCHAR (255) NULL,
    [MD_DATELASTMODIFIED] DATETIME      NULL,
    [MD_ETLJOB]           BIGINT        NULL,
    [MD_ETLEXECUTION]     BIGINT        NULL,
    [MD_ETLRUN]           BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_LH_ROLE] ASC)
);

