CREATE TABLE [dw].[DIM_SECURITYGUARD] (
    [SK_DIM_SECURITYGUARD] BIGINT         IDENTITY (1, 1) NOT NULL,
    [PK_SourceIdStr]       VARCHAR (100)  NULL,
    [PK_SourceId]          BIGINT         NULL,
    [PK_SourceSystem]      NVARCHAR (50)  NOT NULL,
    [FK_Depot]             BIGINT         NULL,
    [FK_Contact]           BIGINT         NULL,
    [FK_Address]           BIGINT         NULL,
    [FK_Employee]          BIGINT         NULL,
    [FK_QA_QUALITYHEADER]  BIGINT         NULL,
    [GuardLocationId]      BIGINT         NULL,
    [GuardContactId]       BIGINT         NULL,
    [GuardAddressId]       BIGINT         NULL,
    [LoginId]              VARCHAR (50)   NULL,
    [COA]                  VARCHAR (100)  NULL,
    [FirstName]            NVARCHAR (255) NULL,
    [MiddleName]           NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NULL,
    [HireDate]             DATE           NULL,
    [TerminationDate]      DATE           NULL,
    [BirthDate]            DATE           NULL,
    [GuardType]            VARCHAR (50)   NULL,
    [Employer]             VARCHAR (30)   NULL,
    [DisplayName]          VARCHAR (100)  NULL,
    [Invited]              BIT            NULL,
    [GuardActive]          BIT            NULL,
    [GuardRole]            VARCHAR (100)  NULL,
    [MD_CreateDate]        DATE           NULL,
    [MD_ModifiedDate]      DATE           NULL,
    [MD_ETLJobCode]        INT            NULL,
    [MD_ETLRunCode]        BIGINT         NULL,
    [MD_ETLRun]            BIGINT         NULL,
    [MD_ModifiedUser]      VARCHAR (100)  NULL,
    CONSTRAINT [PK_DIM_SECURITYGUARD] PRIMARY KEY CLUSTERED ([SK_DIM_SECURITYGUARD] ASC)
);

