CREATE TABLE [dw].[DIM_GHS_USERS_TEAMS] (
    [SK_USERS_TEAMS]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [P_USERS_TEAMS_ID]  BIGINT        NOT NULL,
    [FK_SK_DIM_USERS]   BIGINT        NULL,
    [FK_SK_DIM_TEAMS]   BIGINT        NULL,
    [MD_DATE_CREATED]   DATETIME      NULL,
    [MD_DATE_MODIFIED]  DATETIME      NULL,
    [MD_JOB_CODE]       INT           NULL,
    [MD_RUN_CODE]       BIGINT        NULL,
    [MD_PACK_NAME]      VARCHAR (70)  NULL,
    [MD_MODIFIED_USER]  VARCHAR (100) NULL,
    [MD_LOGICAL_DELETE] SMALLINT      NULL,
    PRIMARY KEY CLUSTERED ([SK_USERS_TEAMS] ASC),
    CONSTRAINT [FK_DIM_GHS_USERS_TEAMS_DIM_GHS_TEAMS] FOREIGN KEY ([FK_SK_DIM_TEAMS]) REFERENCES [dw].[DIM_GHS_TEAMS] ([SK_DIM_TEAMS]),
    CONSTRAINT [FK_DIM_GHS_USERS_TEAMS_DIM_GHS_USERS] FOREIGN KEY ([FK_SK_DIM_USERS]) REFERENCES [dw].[DIM_GHS_USERS] ([SK_DIM_USERS])
);

