CREATE TABLE [dw].[DIM_CLIENTLOCATION] (
    [SK_DIM_CLIENTLOCATION] BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_SourceSystem]       VARCHAR (100) NOT NULL,
    [PK_SystemId]           BIGINT        NULL,
    [FK_DIM_CUSTOMER]       BIGINT        NULL,
    [FK_DIM_DEPOT]          BIGINT        NULL,
    [LocDepotId]            VARCHAR (100) NULL,
    [LocCode]               VARCHAR (100) NOT NULL,
    [LocName]               VARCHAR (100) NOT NULL,
    [LocDebtorCode]         VARCHAR (100) NULL,
    [LocBureauCode]         VARCHAR (100) NULL,
    [LocBureauName]         VARCHAR (100) NULL,
    [LocSuspended]          BIT           NULL,
    [LocSuspendDate]        DATE          NULL,
    [LocSuspendReason]      VARCHAR (100) NULL,
    [LocHasKeys]            BIT           NULL,
    [SubLocName]            VARCHAR (100) NULL,
    [LocShortName]          VARCHAR (100) NULL,
    [LocBranchRef]          VARCHAR (100) NULL,
    [LocActive]             BIT           NULL,
    [MD_CreateDate]         DATETIME      NULL,
    [MD_ModifiedDate]       DATETIME      NULL,
    [MD_ETLJobCode]         INT           NULL,
    [MD_ETLRunCode]         BIGINT        NULL,
    [MD_ETLRun]             BIGINT        NULL,
    [MD_ModifiedUser]       VARCHAR (100) NULL,
    [FK_QA_QUALITYHEADER]   BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_CLIENTLOCATION] ASC)
);

