CREATE TABLE [dw].[DIM_EMPEE] (
    [SK_DIM_Employee]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [P_Oid_clsno]           INT             NOT NULL,
    [P_Oid_instid]          BIGINT          NOT NULL,
    [P_Empid]               VARCHAR (255)   NOT NULL,
    [P_SourceSystem]        VARCHAR (10)    NOT NULL,
    [P_Staffid]             BIGINT          NULL,
    [P_Firstname]           NVARCHAR (50)   NULL,
    [P_Surname]             NVARCHAR (50)   NULL,
    [P_Fullname]            NVARCHAR (75)   NULL,
    [P_Gender]              VARCHAR (1)     NULL,
    [P_Email]               VARCHAR (MAX)   NULL,
    [P_HomePhone]           VARCHAR (50)    NULL,
    [P_BusinessPhone]       VARCHAR (50)    NULL,
    [P_Mobile]              VARCHAR (51)    NULL,
    [P_IsInactive]          BIT             NULL,
    [P_StartDate]           DATE            NULL,
    [P_NextAnniversaryDate] DATE            NULL,
    [P_TerminationDate]     DATE            NULL,
    [P_PayGroup]            VARCHAR (31)    NULL,
    [P_BranchCode]          VARCHAR (7)     NULL,
    [P_DefaultPayCode]      VARCHAR (10)    NULL,
    [P_BaseHourRate]        DECIMAL (14, 4) NULL,
    [P_HrBasis]             VARCHAR (50)    NULL,
    [P_HrType]              VARCHAR (60)    NULL,
    [MD_DATE_CREATED]       DATE            NULL,
    [MD_DATE_MODIFIED]      DATE            NULL,
    [MD_JOB_CODE]           INT             NULL,
    [MD_RUN_CODE]           BIGINT          NULL,
    [MD_PACK_NAME]          VARCHAR (70)    NULL,
    [MD_MODIFIED_USER]      VARCHAR (100)   NULL,
    [MD_LOGICAL_DELETE]     SMALLINT        NULL
);

