CREATE TABLE [dw].[DIM_NV_LOCATION] (
    [SK_LOCATIONID]       INT           IDENTITY (1, 1) NOT NULL,
    [P_LOCATION]          VARCHAR (255) NOT NULL,
    [P_LOCATIONTYPE]      VARCHAR (50)  NULL,
    [MD_DATELASTMODIFIED] DATETIME      NULL,
    [MD_ETLJOB]           BIGINT        NULL,
    [MD_ETLEXECUTION]     BIGINT        NULL,
    [MD_ETLRUN]           BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_LOCATIONID] ASC)
);

