CREATE TABLE [dw].[DIM_ADDRESS] (
    [SK_DIM_ADDRESS]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_SourceSystem]     VARCHAR (100) NOT NULL,
    [PK_SourceId]         BIGINT        NOT NULL,
    [AddName]             VARCHAR (100) NULL,
    [AddUnitNo]           VARCHAR (100) NULL,
    [AddStreetNo]         VARCHAR (100) NULL,
    [AddSuiteNo]          VARCHAR (100) NULL,
    [AddPoBox]            VARCHAR (100) NULL,
    [AddStreet1]          VARCHAR (100) NULL,
    [AddStreet2]          VARCHAR (100) NULL,
    [AddCity]             VARCHAR (100) NULL,
    [AddState]            VARCHAR (100) NULL,
    [AddPostcode]         VARCHAR (100) NULL,
    [AddCountry]          VARCHAR (100) NULL,
    [AddPhone]            VARCHAR (100) NULL,
    [AddSaved]            VARCHAR (100) NULL,
    [AddNotes]            VARCHAR (100) NULL,
    [LINZId]              VARCHAR (100) NULL,
    [GooglePlacesId]      VARCHAR (100) NULL,
    [AddLat]              REAL          NULL,
    [AddLong]             REAL          NULL,
    [MD_CreateDate]       DATETIME      NULL,
    [MD_ModifiedDate]     DATETIME      NULL,
    [MD_ETLJobCode]       INT           NULL,
    [MD_ETLRunCode]       BIGINT        NULL,
    [MD_ETLRun]           BIGINT        NULL,
    [MD_ModifiedUser]     VARCHAR (100) NULL,
    [FK_QA_QUALITYHEADER] BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_ADDRESS] ASC)
);

