CREATE TABLE [dw].[DIM_LH_AREA] (
    [SK_DIM_LH_AREA]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_AREA_ID]          VARCHAR (255) NULL,
    [P_AREA_NAME]         VARCHAR (255) NULL,
    [P_AREA_TYPE]         VARCHAR (255) NULL,
    [P_AREA_PARENT_ID]    VARCHAR (255) NULL,
    [P_AREA_CREATED_AT]   DATETIME      NULL,
    [P_AREA_UPDATED_AT]   DATETIME      NULL,
    [MD_FILENAME]         VARCHAR (255) NULL,
    [MD_DATELASTMODIFIED] DATETIME      NULL,
    [MD_ETLJOB]           BIGINT        NULL,
    [MD_ETLEXECUTION]     BIGINT        NULL,
    [MD_ETLRUN]           BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_LH_AREA] ASC)
);

