CREATE TABLE [dw].[DIM_CUSTOMER] (
    [SK_DIM_CUSTOMER]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_DW_Source_System] VARCHAR (50)  NOT NULL,
    [PK_WS_ClientId]      INT           NOT NULL,
    [FK_DIM_ORGANISATION] BIGINT        NULL,
    [FK_DIM_Suburb]       BIGINT        NULL,
    [P_Client_Code]       VARCHAR (128) NULL,
    [P_Bureau_Code]       VARCHAR (128) NULL,
    [P_Client_Name]       VARCHAR (256) NULL,
    [P_Bureau_Name]       VARCHAR (256) NULL,
    [P_Debtor_Code]       VARCHAR (64)  NULL,
    [P_Address1]          VARCHAR (128) NULL,
    [P_Address2]          VARCHAR (128) NULL,
    [P_City]              VARCHAR (128) NULL,
    [P_MapLat]            FLOAT (53)    NULL,
    [P_MapLong]           FLOAT (53)    NULL,
    [P_IsComplete]        BIT           NULL,
    [P_IsSuspended]       BIT           NULL,
    [P_Suspended_By]      VARCHAR (40)  NULL,
    [P_Suspended_Date]    DATETIME      NULL,
    [P_Suspended_Reason]  VARCHAR (128) NULL,
    [P_Client_Active]     BIT           NULL,
    [P_Has_Keys]          BIT           NULL,
    [MD_DATE_CREATED]     DATETIME      NULL,
    [MD_DATE_MODIFIED]    DATETIME      NULL,
    [MD_JOB_CODE]         INT           NULL,
    [MD_RUN_CODE]         BIGINT        NULL,
    [MD_ETL_RUN]          INT           NULL,
    [MD_LOGICAL_DELETE]   BIT           NULL,
    CONSTRAINT [PK__DIM_CUST__831D4077048ACA11] PRIMARY KEY CLUSTERED ([SK_DIM_CUSTOMER] ASC),
    CONSTRAINT [FK_DIM_CUSTOMER_DIM_ORGANISATION] FOREIGN KEY ([FK_DIM_ORGANISATION]) REFERENCES [dw].[DIM_ORGANISATION] ([SK_DIM_Organisation]),
    CONSTRAINT [FK_DIM_CUSTOMER_DIM_SUBURB] FOREIGN KEY ([FK_DIM_Suburb]) REFERENCES [dw].[DIM_SUBURB] ([SK_DIM_SUBURB])
);

