CREATE TABLE [dw].[DIM_IT_CUSTOMER] (
    [SK_DIM_IT_Customer] BIGINT        IDENTITY (1, 1) NOT NULL,
    [P_CustomerName]     VARCHAR (255) NOT NULL,
    [MD_DATE_CREATED]    DATE          NULL,
    [MD_DATE_MODIFIED]   DATE          NULL,
    [MD_JOB_CODE]        INT           NULL,
    [MD_RUN_CODE]        BIGINT        NULL,
    [MD_PACK_NAME]       VARCHAR (70)  NULL,
    [MD_MODIFIED_USER]   VARCHAR (100) NULL,
    [MD_LOGICAL_DELETE]  SMALLINT      NULL,
    CONSTRAINT [PK_DIM_IT_CUSTOMER] PRIMARY KEY CLUSTERED ([SK_DIM_IT_Customer] ASC)
);

