CREATE TABLE [dw].[DIM_EMPLOYEE] (
    [SK_DIM_EMPLOYEE]           BIGINT       IDENTITY (1, 1) NOT NULL,
    [PK_DW_Source_System]       VARCHAR (50) NOT NULL,
    [PK_PR_ID_Number]           VARCHAR (6)  NULL,
    [PK_YO_ID_Number]           VARCHAR (6)  NULL,
    [PK_GT_ID_Number]           VARCHAR (7)  NULL,
    [PK_GT_Clsno]               INT          NULL,
    [PK_GT_Instid]              INT          NULL,
    [FK_CON_EMPLOYEE]           BIGINT       NULL,
    [FK_DIM_Job]                INT          NULL,
    [FK_DIM_CostActivity]       INT          NULL,
    [FK_DIM_Branch]             VARCHAR (10) NULL,
    [FK_SECURITY_GUARD_LICENCE] VARCHAR (10) NULL,
    [FK_GT_DIM_EMPLOYEE]        BIGINT       NULL,
    [FK_YO_DIM_EMPLOYEE]        BIGINT       NULL,
    [FK_Manager]                BIGINT       NULL,
    [P_First_Name]              VARCHAR (30) NULL,
    [P_Middle_Name]             VARCHAR (30) NULL,
    [P_Surname]                 VARCHAR (50) NULL,
    [P_Other_Name]              VARCHAR (30) NULL,
    [P_Preferred_Name]          VARCHAR (30) NULL,
    [P_Gender]                  VARCHAR (30) NULL,
    [P_Birth_Date]              DATE         NULL,
    [P_Business_Email]          VARCHAR (80) NULL,
    [P_Personal_Email]          VARCHAR (80) NULL,
    [P_Home_Phone]              VARCHAR (15) NULL,
    [P_Work_Phone]              VARCHAR (15) NULL,
    [P_Mobile_Phone]            VARCHAR (15) NULL,
    [P_PR_Status]               VARCHAR (20) NULL,
    [P_PR_Hire_Date]            DATE         NULL,
    [P_PR_Termination_Date]     DATE         NULL,
    [P_Payrun_Group]            VARCHAR (20) NULL,
    [P_Company]                 VARCHAR (8)  NULL,
    [P_Region]                  VARCHAR (8)  NULL,
    [P_Employee_Type]           VARCHAR (8)  NULL,
    [P_AX_CostCentre]           VARCHAR (8)  NULL,
    [P_AX_GLAccount]            VARCHAR (10) NULL,
    [P_Employement_Type]        VARCHAR (1)  NULL,
    [P_Fixed_Term_End]          DATE         NULL,
    [P_LSL_Union_Start]         DATE         NULL,
    [P_Sick_Leave_Start]        DATE         NULL,
    [P_Union_Notes]             DATE         NULL,
    [P_Parental_Leave_Start]    DATE         NULL,
    [P_Parental_Leave_End]      DATE         NULL,
    [MD_DATE_MODIFIED]          DATETIME     NULL,
    [MD_JOB_CODE]               INT          NULL,
    [MD_RUN_CODE]               BIGINT       NULL,
    [MD_ETL_RUN]                INT          NULL,
    [MD_LOGICAL_DELETE]         BIT          NULL,
    PRIMARY KEY CLUSTERED ([SK_DIM_EMPLOYEE] ASC),
    CONSTRAINT [FK_DIM_EMPLOYEE_CON_EMPLOYEE] FOREIGN KEY ([FK_CON_EMPLOYEE]) REFERENCES [dw].[CON_EMPLOYEE] ([SK_CON_EMPLOYEE])
);

