CREATE TABLE [dw].[FACT_DRAFTBUDGET] (
    [PK_ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [FK_DIM_GT_PERIOD]    INT             NULL,
    [FK_DIM_JOB]          BIGINT          NULL,
    [FK_DIM_GT_GL]        INT             NULL,
    [FK_DIM_ORGANISATION] BIGINT          NULL,
    [Amount]              NUMERIC (18, 2) NULL,
    [source]              VARCHAR (20)    NULL,
    CONSTRAINT [PK__FACT_DRA__F4A24BC2BDD255BF] PRIMARY KEY CLUSTERED ([PK_ID] ASC),
    CONSTRAINT [FK_FACT_DRAFTBUDGET_DIM_GT_GL] FOREIGN KEY ([FK_DIM_GT_GL]) REFERENCES [dw].[DIM_GT_GL] ([SK_DIM_GT_GL]),
    CONSTRAINT [FK_FACT_DRAFTBUDGET_DIM_GT_PERIOD] FOREIGN KEY ([FK_DIM_GT_PERIOD]) REFERENCES [dw].[DIM_GT_PERIOD] ([SK_DIM_GT_PERIOD]),
    CONSTRAINT [FK_FACT_DRAFTBUDGET_DIM_JOB] FOREIGN KEY ([FK_DIM_JOB]) REFERENCES [dw].[DIM_JOB] ([SK_DIM_JOB]),
    CONSTRAINT [FK_FACT_DRAFTBUDGET_DIM_ORGANISATION] FOREIGN KEY ([FK_DIM_ORGANISATION]) REFERENCES [dw].[DIM_ORGANISATION] ([SK_DIM_Organisation])
);

