CREATE TABLE [dw].[FACT_LH_TASK_DETAILS] (
    [PK_TASK_ID]    VARCHAR (255) NOT NULL,
    [P_FIELD_ID]    VARCHAR (MAX) NULL,
    [P_FIELD_LABEL] VARCHAR (MAX) NULL,
    [P_FIELD_VALUE] VARCHAR (MAX) NULL
);

