CREATE TABLE [dw].[FACT_LH_EVENT] (
    [SK_FACT_EVENT]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_EVENT_ID]         VARCHAR (255) NULL,
    [FK_SK_AREA]          BIGINT        NULL,
    [FK_SK_AREA_LOCATION] BIGINT        NULL,
    [FK_SK_USER]          BIGINT        NULL,
    [P_USERNAME]          VARCHAR (255) NULL,
    [FK_SK_CREATEDAT]     BIGINT        NULL,
    [P_TIMESTAMP]         TIME (7)      NULL,
    [P_LATITUDE]          FLOAT (53)    NULL,
    [P_LONGITUDE]         FLOAT (53)    NULL,
    [P_TYPE]              VARCHAR (255) NULL,
    [MD_FILENAME]         VARCHAR (255) NULL,
    [MD_DATELASTMODIFIED] DATETIME      NULL,
    [MD_ETLJOB]           VARCHAR (255) NULL,
    [MD_ETLEXECUTION]     VARCHAR (255) NULL,
    [MD_ETLRUN]           VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_EVENT] ASC),
    CONSTRAINT [FK_FACT_LH_EVENT_DIM_DATE] FOREIGN KEY ([FK_SK_CREATEDAT]) REFERENCES [dw].[DIM_DATE] ([SK_DIM_DATE]),
    CONSTRAINT [FK_FACT_LH_EVENT_DIM_LH_AREA] FOREIGN KEY ([FK_SK_AREA]) REFERENCES [dw].[DIM_LH_AREA] ([SK_DIM_LH_AREA]),
    CONSTRAINT [FK_FACT_LH_EVENT_DIM_LH_AREA_LOCATION] FOREIGN KEY ([FK_SK_AREA_LOCATION]) REFERENCES [dw].[DIM_LH_AREA] ([SK_DIM_LH_AREA]),
    CONSTRAINT [FK_FACT_LH_EVENT_DIM_LH_USER] FOREIGN KEY ([FK_SK_USER]) REFERENCES [dw].[DIM_LH_USER] ([SK_DIM_LH_USER])
);

