CREATE TABLE [dw].[FACT_LH_ISSUE_DETAILS] (
    [PK_ISSUE_ID]        VARCHAR (255) NULL,
    [P_FORM_GROUP_LABEL] VARCHAR (MAX) NULL,
    [P_FIELD_LABEL]      VARCHAR (MAX) NULL,
    [P_FIELD_VALUE]      VARCHAR (MAX) NULL
);

