CREATE TABLE [dw].[FACT_GHS_ACTIVITIES] (
    [SK_FACT_ACTIVITIES]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_ACTIVITY_ID]              BIGINT        NULL,
    [FK_SK_DIM_DATE]              BIGINT        NULL,
    [FK_SK_DIM_USERS]             BIGINT        NULL,
    [FK_SK_DIM_ORGANISATIONS]     BIGINT        NULL,
    [P_NAME]                      VARCHAR (256) NULL,
    [P_REFERENCE]                 VARCHAR (256) NULL,
    [P_NOTES]                     VARCHAR (256) NULL,
    [P_STATUS]                    VARCHAR (256) NULL,
    [P_TYPE]                      VARCHAR (256) NULL,
    [P_TYPE_CATEGORY]             VARCHAR (256) NULL,
    [P_START_TIME]                DATETIME      NULL,
    [P_FINISH_TIME]               DATETIME      NULL,
    [P_SCHEDULED_START_TIME]      DATETIME      NULL,
    [P_SCHEDULED_FINISH_TIME]     DATETIME      NULL,
    [P_IS_PLANNED]                BIT           NULL,
    [P_IS_FAVOURITE]              BIT           NULL,
    [P_IS_ROUND_TRIP]             BIT           NULL,
    [P_IS_ALERTED]                BIT           NULL,
    [P_WAS_ALERTED]               BIT           NULL,
    [P_IS_ONGOING]                BIT           NULL,
    [P_IS_ARCHIVED]               BIT           NULL,
    [P_START_LATITUDE]            FLOAT (53)    NULL,
    [P_START_LONGITUDE]           FLOAT (53)    NULL,
    [P_START_ADDRESS]             VARCHAR (256) NULL,
    [P_DESTINATION_LATITUDE]      FLOAT (53)    NULL,
    [P_DESTINATION_LONGITUDE]     FLOAT (53)    NULL,
    [P_DESTINATION_ADDRESS]       VARCHAR (500) NULL,
    [P_TIMER_TYPE]                VARCHAR (256) NULL,
    [P_TIMER_TOD_TIME]            VARCHAR (256) NULL,
    [P_REMINDER_THRESHOLD]        BIGINT        NULL,
    [P_TIMER_INTERVAL_MINUTES]    BIGINT        NULL,
    [P_DASHBOARD_URL]             VARCHAR (256) NULL,
    [P_TRACKER_URL]               VARCHAR (256) NULL,
    [P_CREATED_AT]                DATETIME      NULL,
    [P_UPDATED_AT]                DATETIME      NULL,
    [P_GOT_IN_TROUBLE_AT]         DATETIME      NULL,
    [P_IS_FOLLOWED_UP]            BIT           NULL,
    [P_IS_FOLLOWED_UP_COMPLETED]  BIT           NULL,
    [P_APPROVAL_STATUS]           VARCHAR (256) NULL,
    [P_V_BTTN_SERIAL_NUMBER]      VARCHAR (256) NULL,
    [P_DURATION_SECONDS]          BIGINT        NULL,
    [P_TOTAL_DISTANCE_METRES]     BIGINT        NULL,
    [P_AUTO_CHECKIN_COUNT]        BIGINT        NULL,
    [P_MANUAL_CHECKIN_COUNT]      BIGINT        NULL,
    [P_HASHTAG_CHECKIN_COUNT]     BIGINT        NULL,
    [P_GPS_CHECKIN_COUNT]         BIGINT        NULL,
    [P_VEHICLE_CHECKIN_COUNT]     BIGINT        NULL,
    [P_ESTIMATED_DISTANCE_METRES] BIGINT        NULL,
    [P_ACCURACY_AVG_METRES]       FLOAT (53)    NULL,
    [P_ALTITUDE_AVG_METRES]       FLOAT (53)    NULL,
    [P_ALTITUDE_MED_METRES]       FLOAT (53)    NULL,
    [P_ALTITUDE_MIN_METRES]       FLOAT (53)    NULL,
    [P_ALTITUDE_MAX_METRES]       FLOAT (53)    NULL,
    [P_SPEED_AVG_KMH]             FLOAT (53)    NULL,
    [P_SPEED_MED_KMH]             FLOAT (53)    NULL,
    [P_SPEED_MIN_KMH]             FLOAT (53)    NULL,
    [P_SPEED_MAX_KMH]             FLOAT (53)    NULL,
    [MD_DATE_CREATED]             DATETIME      NULL,
    [MD_DATE_MODIFIED]            DATETIME      NULL,
    [MD_JOB_CODE]                 INT           NULL,
    [MD_RUN_CODE]                 BIGINT        NULL,
    [MD_PACK_NAME]                VARCHAR (70)  NULL,
    [MD_MODIFIED_USER]            VARCHAR (100) NULL,
    [MD_LOGICAL_DELETE]           SMALLINT      NULL,
    CONSTRAINT [PK_ACTIVITY_ID] PRIMARY KEY CLUSTERED ([SK_FACT_ACTIVITIES] ASC),
    CONSTRAINT [FK_FACT_GHS_ACTIVITIES_DIM_DATE] FOREIGN KEY ([FK_SK_DIM_DATE]) REFERENCES [dw].[DIM_DATE] ([SK_DIM_DATE]),
    CONSTRAINT [FK_FACT_GHS_ACTIVITIES_DIM_GHS_USERS] FOREIGN KEY ([FK_SK_DIM_USERS]) REFERENCES [dw].[DIM_GHS_USERS] ([SK_DIM_USERS])
);

