CREATE TABLE [dw].[FACT_NV_ACTIVITY] (
    [SK_ACTIVITYID]          INT             IDENTITY (1, 1) NOT NULL,
    [FK_LOCATIONID]          INT             NULL,
    [FK_DRIVERID]            INT             NULL,
    [FK_VEHICLEID]           INT             NULL,
    [FK_OWNERID]             INT             NULL,
    [FK_REGIONID]            INT             NULL,
    [FK_AREAID]              INT             NULL,
    [PK_ACTIVITYDATETIME]    DATETIME        NOT NULL,
    [P_LATITUDE]             DECIMAL (10, 7) NOT NULL,
    [P_LONGITUDE]            DECIMAL (10, 7) NOT NULL,
    [P_GPSVALID]             BIT             NOT NULL,
    [P_ONSITETIME]           INT             NULL,
    [P_IGNITIONON]           BIT             NULL,
    [P_SPEED]                DECIMAL (5, 2)  NULL,
    [P_INCREMENTALDISTANCE]  DECIMAL (10, 5) NULL,
    [P_ODOMETER]             DECIMAL (10, 2) NULL,
    [P_TRIPDISTANCE]         DECIMAL (10, 2) NULL,
    [P_MAXSPEED]             DECIMAL (5, 2)  NULL,
    [P_HDOP]                 DECIMAL (5, 2)  NULL,
    [P_NUMSATELLITES]        INT             NULL,
    [P_OFFROADMETERS]        DECIMAL (10, 2) NULL,
    [P_DEGREESBEARING]       DECIMAL (5, 2)  NULL,
    [P_COMMUNICATIONCHANNEL] VARCHAR (50)    NULL,
    [P_ISTOLLWAY]            BIT             NULL,
    [P_EVENTTYPEDESCRIPTION] VARCHAR (255)   NULL,
    [P_OUTOFORDER]           BIT             NULL,
    [FK_EVENTPRIORITY]       VARCHAR (50)    NULL,
    [MD_FILENAME]            VARCHAR (255)   NULL,
    [MD_DATELASTMODIFIED]    DATETIME        NULL,
    [MD_ETLJOB]              BIGINT          NULL,
    [MD_ETLEXECUTION]        BIGINT          NULL,
    [MD_ETLRUN]              BIGINT          NULL,
    PRIMARY KEY CLUSTERED ([SK_ACTIVITYID] ASC)
);

