CREATE TABLE [dw].[FACT_DESPATCH] (
    [SK_FACT_DESPATCH]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [PK_DW_SOURCE_SYSTEM]         VARCHAR (50)    NULL,
    [PK_WS_DespatchId]            INT             NULL,
    [FK_DIM_CUSTOMER]             BIGINT          NULL,
    [FK_DIM_DESPATCH_TYPE]        BIGINT          NULL,
    [FK_DIM_DESPATCH_ZONE]        INT             NULL,
    [FK_DIM_MONITOR_CENTRE]       INT             NULL,
    [FK_DIM_SECURITY_GUARD]       BIGINT          NULL,
    [FK_DIM_PATROL_SETUP]         BIGINT          NULL,
    [P_Monitoring_Despatcher]     VARCHAR (128)   NULL,
    [P_Despatch_DateTime]         DATETIME        NULL,
    [P_Acknowledge_DateTime]      DATETIME        NULL,
    [P_OnSite_DateTime]           DATETIME        NULL,
    [P_OffSite_DateTime]          DATETIME        NULL,
    [P_Response_Minutes]          INT             NULL,
    [P_Acknowledge_Minutes]       INT             NULL,
    [P_OnSite_Minutes]            INT             NULL,
    [P_Charge_ExGST]              NUMERIC (10, 2) NULL,
    [P_Client_Patrol_Charge]      NUMERIC (10, 2) NULL,
    [P_Casual_Charge_Type]        VARCHAR (14)    NULL,
    [P_Missed_Count]              INT             NULL,
    [P_Total_Count]               INT             NULL,
    [P_IsIncident_Report]         BIT             NULL,
    [P_Onsite_Distance_From_Site] VARCHAR (64)    NULL,
    [P_Onsite_Lat]                VARCHAR (64)    NULL,
    [P_Onsite_Long]               VARCHAR (64)    NULL,
    [P_response_NoCharge]         BIT             NULL,
    [P_Purchase_Order_No]         VARCHAR (128)   NULL,
    [P_Job_Text]                  VARCHAR (MAX)   NULL,
    [P_Special_Instructions]      VARCHAR (MAX)   NULL,
    [P_Patrol_Resolution]         VARCHAR (MAX)   NULL,
    [P_Patrol_Complete_Status]    VARCHAR (20)    NULL,
    [P_HasPhotos]                 BIT             NULL,
    [MD_DATE_MODIFIED]            DATETIME        NULL,
    [MD_JOB_CODE]                 INT             NULL,
    [MD_RUN_CODE]                 BIGINT          NULL,
    [MD_ETL_RUN]                  INT             NULL,
    [MD_LOGICAL_DELETE]           BIT             NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_DESPATCH] ASC),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_CUSTOMER] FOREIGN KEY ([FK_DIM_CUSTOMER]) REFERENCES [dw].[DIM_CUSTOMER] ([SK_DIM_CUSTOMER]),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_DESPATCH_TYPE] FOREIGN KEY ([FK_DIM_DESPATCH_TYPE]) REFERENCES [dw].[DIM_DESPATCH_TYPE] ([SK_DIM_DESPATCH_TYPE]),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_DESPATCH_ZONE] FOREIGN KEY ([FK_DIM_DESPATCH_ZONE]) REFERENCES [dw].[DIM_DESPATCH_ZONE] ([SK_DIM_DESPATCH_ZONE]),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_MONITOR_CENTRE] FOREIGN KEY ([FK_DIM_MONITOR_CENTRE]) REFERENCES [dw].[DIM_MONITOR_CENTRE] ([SK_DIM_MONITOR_CENTRE]),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_PATROL_SETUP] FOREIGN KEY ([FK_DIM_PATROL_SETUP]) REFERENCES [dw].[DIM_PATROL_SETUP] ([SK_DIM_PATROL_SETUP]),
    CONSTRAINT [FK_FACT_DESPATCH_DIM_SECURITYGUARD] FOREIGN KEY ([FK_DIM_SECURITY_GUARD]) REFERENCES [dw].[DIM_SECURITYGUARD] ([SK_DIM_SECURITYGUARD])
);

