CREATE TABLE [dw].[FACT_ROSTER] (
    [SK_FACT_ROSTER]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_SourceSystem]        VARCHAR (100) NULL,
    [PK_SourceId]            BIGINT        NULL,
    [FK_DIM_DATE]            BIGINT        NULL,
    [FK_DIM_SECURITYGUARD]   BIGINT        NULL,
    [FK_DIM_IT_ACTIVITY]     BIGINT        NULL,
    [FK_DIM_CUSTOMER]        BIGINT        NULL,
    [FK_DIM_IT_LOCSUBBRANCH] BIGINT        NULL,
    [FK_DIM_COST_ACTIVITY]   BIGINT        NULL,
    [FK_DIM_LEAVETYPE]       BIGINT        NULL,
    [FK_DIM_AREA]            BIGINT        NULL,
    [FK_FACT_TIMESHEET]      BIGINT        NULL,
    [RosterGuardId]          BIGINT        NULL,
    [RosterAreaId]           BIGINT        NULL,
    [RosterTimesheetId]      BIGINT        NULL,
    [RosterFrom]             DATETIME      NULL,
    [RosterTo]               DATETIME      NULL,
    [RosterHrs]              FLOAT (53)    NULL,
    [RosterBreakHrs]         FLOAT (53)    NULL,
    [RosterSalesPerHr]       FLOAT (53)    NULL,
    [RosterCostPerHr]        FLOAT (53)    NULL,
    [RosterTotalCost]        FLOAT (53)    NULL,
    [RosterWarning]          VARCHAR (100) NULL,
    [RosterWarningOr]        BIT           NULL,
    [RosterWarningOrBy]      VARCHAR (100) NULL,
    [RosterPublished]        BIT           NULL,
    [RosterOpen]             BIT           NULL,
    [RosterPO]               VARCHAR (100) NULL,
    [RosterRITM]             VARCHAR (100) NULL,
    [RosterEMSMin]           INT           NULL,
    [RosterNCRMin]           INT           NULL,
    [MD_CreateDate]          DATETIME      NULL,
    [MD_ModifiedDate]        DATETIME      NULL,
    [MD_ETLJobCode]          INT           NULL,
    [MD_ETLRunCode]          BIGINT        NULL,
    [MD_ETLRun]              BIGINT        NULL,
    [MD_ModifiedUser]        VARCHAR (100) NULL,
    [MD_LogicalDelete]       BIT           NULL,
    [FK_QA_QUALITYHEADER]    BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_ROSTER] ASC),
    CONSTRAINT [FK_FACT_ROSTER_DIM_COST_ACTIVITY] FOREIGN KEY ([FK_DIM_COST_ACTIVITY]) REFERENCES [dw].[DIM_COST_ACTIVITY] ([SK_DIM_Cost_Activity]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_DATE] FOREIGN KEY ([FK_DIM_DATE]) REFERENCES [dw].[DIM_DATE] ([SK_DIM_DATE]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_IT_ACTIVITY] FOREIGN KEY ([FK_DIM_IT_ACTIVITY]) REFERENCES [dw].[DIM_IT_ACTIVITY] ([SK_DIM_IT_Activity]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_IT_CUSTOMER] FOREIGN KEY ([FK_DIM_CUSTOMER]) REFERENCES [dw].[DIM_IT_CUSTOMER] ([SK_DIM_IT_Customer]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_IT_LOCSUBBRANCH] FOREIGN KEY ([FK_DIM_IT_LOCSUBBRANCH]) REFERENCES [dw].[DIM_IT_LOCSUBBRANCH] ([SK_DIM_IT_LocSubBranch]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_LEAVETYPE] FOREIGN KEY ([FK_DIM_LEAVETYPE]) REFERENCES [dw].[DIM_LEAVETYPE] ([SK_DIM_LEAVETYPE]),
    CONSTRAINT [FK_FACT_ROSTER_DIM_SECURITYGUARD] FOREIGN KEY ([FK_DIM_SECURITYGUARD]) REFERENCES [dw].[DIM_SECURITYGUARD] ([SK_DIM_SECURITYGUARD])
);

