CREATE TABLE [dw].[FACT_TIMESHEET] (
    [PK_DeputyId]             BIGINT        NOT NULL,
    [FK_DIM_DATE]             BIGINT        NULL,
    [FK_FACT_ROSTER]          BIGINT        NULL,
    [FK_DIM_SECURITYGUARD]    BIGINT        NULL,
    [FK_DIM_GUARDAGREEMENT]   BIGINT        NULL,
    [FK_FACT_LEAVELINE]       BIGINT        NULL,
    [FK_LEAVE_TYPE]           BIGINT        NULL,
    [FK_DIM_AREA]             BIGINT        NULL,
    [FK_DIM_COST_ACTIVITY_OR] BIGINT        NULL,
    [FK_DIM_JOB_PAY_OR]       BIGINT        NULL,
    [FK_DIM_JOB_BILL_OR]      BIGINT        NULL,
    [FK_DIM_PAYCODE_OR]       BIGINT        NULL,
    [FK_FACT_TS_EXTRACT]      BIGINT        NULL,
    [TMRosterId]              BIGINT        NULL,
    [TMGuardId]               BIGINT        NULL,
    [TMActivityOverrride]     BIGINT        NULL,
    [TMPayJobOverride]        BIGINT        NULL,
    [TMBillJobOverride]       BIGINT        NULL,
    [TMPaycodeOverride]       BIGINT        NULL,
    [TMPurchaseOrder]         VARCHAR (100) NULL,
    [TMRITM]                  VARCHAR (100) NULL,
    [TMEMSMinutes]            INT           NULL,
    [TMNCRMinutes]            INT           NULL,
    [TMDateFrom]              DATETIME      NULL,
    [TMDateTo]                DATETIME      NULL,
    [TMBreakHours]            FLOAT (53)    NULL,
    [TMBreakType]             VARCHAR (100) NULL,
    [TMHours]                 FLOAT (53)    NULL,
    [TMCost]                  FLOAT (53)    NULL,
    [TMJobCostPerHour]        FLOAT (53)    NULL,
    [TMJobSalesPerHour]       FLOAT (53)    NULL,
    [TMBaseCostPerHour]       FLOAT (53)    NULL,
    [TMSourceType]            VARCHAR (100) NULL,
    [TMRealTime]              BIT           NULL,
    [TMAutoTimeApproved]      BIT           NULL,
    [TMAutoPayApproved]       BIT           NULL,
    [TMTimeApproved]          BIT           NULL,
    [TMPayApproved]           BIT           NULL,
    [TMExported]              BIT           NULL,
    [TMFinal]                 BIT           NULL,
    [TMInvoiced]              BIT           NULL,
    [TMInvoiceRef]            VARCHAR (100) NULL,
    [TMDiscarded]             BIT           NULL,
    [TMHasPayCycle]           BIT           NULL,
    [MD_ExportedDate]         DATETIME      NULL,
    [MD_FinalDate]            DATETIME      NULL,
    [MD_InvoicedDate]         DATETIME      NULL,
    [MD_CreateDate]           DATETIME      NULL,
    [MD_ModifiedDate]         DATETIME      NULL,
    [MD_ProcessedLate]        BIT           NULL,
    [MD_HistoricAdj]          BIT           NULL,
    [MD_PayrollExclude]       BIT           NULL,
    [MD_ETLJobCode]           INT           NULL,
    [MD_ETLRunCode]           BIGINT        NULL,
    [MD_ETLRun]               BIGINT        NULL,
    [MD_ModifiedUser]         VARCHAR (100) NULL,
    [FK_QA_QUALITYHEADER]     BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([PK_DeputyId] ASC)
);

