CREATE TABLE [dw].[FACT_GLTRANS] (
    [SK_FACT_GLTRANS]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [FK_DIM_DATE_POSTING]   BIGINT          NOT NULL,
    [FK_DIM_GT_GL]          INT             NOT NULL,
    [FK_DIM_GT_PERIOD]      INT             NOT NULL,
    [FK_DIM_COST_ACTIVITY]  BIGINT          NOT NULL,
    [FK_DIM_JOB]            BIGINT          NOT NULL,
    [FK_DIM_ORGANISATION]   BIGINT          NOT NULL,
    [PK_DW_Source_System]   VARCHAR (50)    NOT NULL,
    [PK_oid_clsno]          INT             NULL,
    [PK_oid_instid]         BIGINT          NULL,
    [P_Reference]           VARCHAR (20)    NULL,
    [P_Posting_Date]        DATE            NULL,
    [P_Document_Date]       DATE            NULL,
    [P_Transaction_Type]    VARCHAR (30)    NULL,
    [P_Transaction_Detail]  VARCHAR (30)    NULL,
    [P_Transaction_Subcode] VARCHAR (20)    NULL,
    [P_Narration]           VARCHAR (MAX)   NULL,
    [P_Quantity]            NUMERIC (14, 2) NULL,
    [P_Amount_Net]          NUMERIC (14, 2) NULL,
    [MD_MODIFIED_USER]      VARCHAR (30)    NULL,
    [MD_DATE_MODIFIED]      DATE            NULL,
    [MD_JOB_CODE]           INT             NULL,
    [MD_RUN_CODE]           BIGINT          NULL,
    [MD_ETL_RUN]            INT             NULL,
    [MD_LOGICAL_DELETE]     BIT             NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_GLTRANS] ASC),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_COST_ACTIVITY] FOREIGN KEY ([FK_DIM_COST_ACTIVITY]) REFERENCES [dw].[DIM_COST_ACTIVITY] ([SK_DIM_Cost_Activity]),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_DATE] FOREIGN KEY ([FK_DIM_DATE_POSTING]) REFERENCES [dw].[DIM_DATE] ([SK_DIM_DATE]),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_GT_GL] FOREIGN KEY ([FK_DIM_GT_GL]) REFERENCES [dw].[DIM_GT_GL] ([SK_DIM_GT_GL]),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_GT_PERIOD] FOREIGN KEY ([FK_DIM_GT_PERIOD]) REFERENCES [dw].[DIM_GT_PERIOD] ([SK_DIM_GT_PERIOD]),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_JOB] FOREIGN KEY ([FK_DIM_JOB]) REFERENCES [dw].[DIM_JOB] ([SK_DIM_JOB]),
    CONSTRAINT [FK_FACT_GLTRANS_DIM_ORGANISATION] FOREIGN KEY ([FK_DIM_ORGANISATION]) REFERENCES [dw].[DIM_ORGANISATION] ([SK_DIM_Organisation])
);

