CREATE TABLE [dw].[FACT_BUDGET] (
    [SK_FACT_BUDGET]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [FK_DIM_GT_PERIOD]    INT             NOT NULL,
    [FK_DIM_JOB]          BIGINT          NOT NULL,
    [FK_DIM_ORGANISATION] BIGINT          NOT NULL,
    [FK_DIM_GT_GL]        INT             NOT NULL,
    [total]               NUMERIC (14, 2) NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_BUDGET] ASC),
    CONSTRAINT [FK_FACT_BUDGET_DIM_GT_GL] FOREIGN KEY ([FK_DIM_GT_GL]) REFERENCES [dw].[DIM_GT_GL] ([SK_DIM_GT_GL]),
    CONSTRAINT [FK_FACT_BUDGET_DIM_GT_PERIOD] FOREIGN KEY ([FK_DIM_GT_PERIOD]) REFERENCES [dw].[DIM_GT_PERIOD] ([SK_DIM_GT_PERIOD]),
    CONSTRAINT [FK_FACT_BUDGET_DIM_JOB] FOREIGN KEY ([FK_DIM_JOB]) REFERENCES [dw].[DIM_JOB] ([SK_DIM_JOB]),
    CONSTRAINT [FK_FACT_BUDGET_DIM_ORGANISATION] FOREIGN KEY ([FK_DIM_ORGANISATION]) REFERENCES [dw].[DIM_ORGANISATION] ([SK_DIM_Organisation])
);

