CREATE TABLE [dw].[FACT_LH_EXCEPTION] (
    [SK_FACT_EXCEPTION]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [PK_EXCEPTION_ID]        VARCHAR (255) NULL,
    [FK_SK_AREA]             BIGINT        NULL,
    [FK_SK_AREA_LOCATION]    BIGINT        NULL,
    [P_AREA_NAME]            VARCHAR (255) NULL,
    [P_SCHEDULE_ID]          VARCHAR (255) NULL,
    [P_SCHEDULE_NAME]        VARCHAR (255) NULL,
    [P_SCHEDULE_TYPE]        VARCHAR (255) NULL,
    [P_EXCEPTION_DURATION]   VARCHAR (255) NULL,
    [P_EXCEPTION_OPENED]     DATETIME      NULL,
    [P_EXCEPTION_CREATED_AT] DATETIME      NULL,
    [P_EXCEPTION_UPDATED_AT] DATETIME      NULL,
    [MD_FILENAME]            VARCHAR (255) NULL,
    [MD_DATELASTMODIFIED]    DATETIME      NULL,
    [MD_ETLJOB]              BIGINT        NULL,
    [MD_ETLEXECUTION]        BIGINT        NULL,
    [MD_ETLRUN]              BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_EXCEPTION] ASC),
    CONSTRAINT [FK_FACT_LH_EXCEPTION_DIM_LH_AREA] FOREIGN KEY ([FK_SK_AREA]) REFERENCES [dw].[DIM_LH_AREA] ([SK_DIM_LH_AREA]),
    CONSTRAINT [FK_FACT_LH_EXCEPTION_DIM_LH_AREA_LOCATION] FOREIGN KEY ([FK_SK_AREA_LOCATION]) REFERENCES [dw].[DIM_LH_AREA] ([SK_DIM_LH_AREA])
);

