
create view dw.FACT_CHP_PAYROLL as

SELECT				p.*
FROM				dw.FACT_PAYROLL p
INNER JOIN			(
SELECT				e.*
FROM				dw.DIM_EMPLOYEE e
INNER JOIN			dw.FACT_PAYROLL p ON e.SK_DIM_EMPLOYEE = p.FK_DIM_EMPLOYEE
INNER JOIN			dw.DIM_PAYCODE pc ON p.FK_DIM_PAYCODE = pc.SK_DIM_Paycode
INNER JOIN			dw.CON_PAYCODE cpc ON pc.FK_CON_Paycode = cpc.SK_CON_Paycode
WHERE				SK_CON_Paycode = 16
					) e ON p.FK_DIM_EMPLOYEE = e.SK_DIM_EMPLOYEE
