CREATE TABLE [dw].[FACT_PAYROLL] (
    [SK_FACT_PAYROLL]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [PK_DW_Source_System]  VARCHAR (50)    NOT NULL,
    [PK_GT_clsNo]          INT             NULL,
    [PK_GT_instId]         BIGINT          NULL,
    [PK_PR_payLineId]      BIGINT          NULL,
    [FK_DIM_EMPLOYEE]      BIGINT          NOT NULL,
    [FK_DIM_JOB]           BIGINT          NULL,
    [FK_DIM_PAYCODE]       INT             NOT NULL,
    [FK_DIM_COST_ACTIVITY] BIGINT          NULL,
    [FK_DIM_DATE]          BIGINT          NOT NULL,
    [FK_DIM_BRANCH]        INT             NOT NULL,
    [FK_DIM_BUSINESS]      INT             NOT NULL,
    [FK_DIM_LEAVE_REASON]  INT             NULL,
    [FK_DIM_COSTCENTRE]    INT             NULL,
    [P_Gl_Journal_Ref]     VARCHAR (20)    NULL,
    [P_PayslipId]          BIGINT          NULL,
    [P_PostingDate]        DATE            NULL,
    [P_CostingDate]        DATE            NULL,
    [P_BatchNo]            INT             NULL,
    [P_PayrunGroup]        VARCHAR (2)     NULL,
    [P_AssignmentRef]      VARCHAR (20)    NULL,
    [P_Notes]              VARCHAR (500)   NULL,
    [P_IntimeLocation]     VARCHAR (11)    NULL,
    [P_WorkArea]           VARCHAR (11)    NULL,
    [P_HoursVol]           NUMERIC (11, 5) NULL,
    [P_LeaveUnits]         NUMERIC (11, 5) NULL,
    [P_RatePay]            NUMERIC (11, 5) NULL,
    [P_isRateOverride]     BIT             NULL,
    [P_TotalPay]           NUMERIC (15, 5) NULL,
    [MD_DATE_MODIFIED]     DATETIME        NULL,
    [MD_JOB_CODE]          INT             NULL,
    [MD_RUN_CODE]          BIGINT          NULL,
    [MD_ETL_RUN]           INT             NULL,
    [MD_LOGICAL_DELETE]    BIT             NULL,
    PRIMARY KEY CLUSTERED ([SK_FACT_PAYROLL] ASC),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_BRANCH] FOREIGN KEY ([FK_DIM_BRANCH]) REFERENCES [dw].[DIM_BRANCH] ([SK_DIM_BRANCH]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_BUSINESS] FOREIGN KEY ([FK_DIM_BUSINESS]) REFERENCES [dw].[DIM_BUSINESS] ([SK_DIM_BUSINESS]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_COST_ACTIVITY] FOREIGN KEY ([FK_DIM_COST_ACTIVITY]) REFERENCES [dw].[DIM_COST_ACTIVITY] ([SK_DIM_Cost_Activity]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_DATE] FOREIGN KEY ([FK_DIM_DATE]) REFERENCES [dw].[DIM_DATE] ([SK_DIM_DATE]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_EMPLOYEE] FOREIGN KEY ([FK_DIM_EMPLOYEE]) REFERENCES [dw].[DIM_EMPLOYEE] ([SK_DIM_EMPLOYEE]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_JOB] FOREIGN KEY ([FK_DIM_JOB]) REFERENCES [dw].[DIM_JOB] ([SK_DIM_JOB]),
    CONSTRAINT [FK_FACT_PAYROLL_DIM_PAYCODE] FOREIGN KEY ([FK_DIM_PAYCODE]) REFERENCES [dw].[DIM_PAYCODE] ([SK_DIM_Paycode])
);

