CREATE TABLE [staging].[DIM_PR_EMPLOYEE] (
    [idNumber]             VARCHAR (6)     NULL,
    [firstName]            VARCHAR (30)    NULL,
    [middleName]           VARCHAR (30)    NULL,
    [surname]              VARCHAR (50)    NULL,
    [otherName]            VARCHAR (30)    NULL,
    [preferredName]        VARCHAR (30)    NULL,
    [gender]               VARCHAR (1)     NULL,
    [dateOfBirth]          DATE            NULL,
    [businessEmail]        VARCHAR (80)    NULL,
    [personalEmail]        VARCHAR (80)    NULL,
    [homePhone]            VARCHAR (15)    NULL,
    [workPhone]            VARCHAR (15)    NULL,
    [mobilePhone]          VARCHAR (15)    NULL,
    [status]               VARCHAR (1)     NULL,
    [hireDate]             DATE            NULL,
    [adjServDate]          DATE            NULL,
    [termDate]             DATE            NULL,
    [payRunGroup]          VARCHAR (4)     NULL,
    [company]              VARCHAR (8)     NULL,
    [region]               VARCHAR (8)     NULL,
    [glMap]                VARCHAR (8)     NULL,
    [prAccess]             VARCHAR (8)     NULL,
    [empType]              VARCHAR (8)     NULL,
    [department]           VARCHAR (8)     NULL,
    [account]              VARCHAR (10)    NULL,
    [labourCostCode1]      VARCHAR (10)    NULL,
    [labourCostCode2]      VARCHAR (10)    NULL,
    [autoPayHoursType]     VARCHAR (2)     NULL,
    [costingMethod]        VARCHAR (1)     NULL,
    [basePayRateFrequency] VARCHAR (1)     NULL,
    [baseHoursAmount]      REAL            NULL,
    [payFrequency]         VARCHAR (1)     NULL,
    [payRate1]             NUMERIC (15, 5) NULL,
    [payRate2]             NUMERIC (11, 4) NULL,
    [payRate3]             NUMERIC (11, 4) NULL,
    [payRate4]             NUMERIC (11, 4) NULL,
    [employmentType]       VARCHAR (1)     NULL,
    [userField1]           NUMERIC (5, 2)  NULL,
    [userField2]           NUMERIC (5, 2)  NULL,
    [userField3]           VARCHAR (5)     NULL,
    [userField4]           VARCHAR (5)     NULL,
    [userField5]           VARCHAR (10)    NULL,
    [userField6]           VARCHAR (10)    NULL,
    [userField7]           VARCHAR (15)    NULL,
    [userField8]           NUMERIC (7, 5)  NULL,
    [userField9]           NUMERIC (7, 3)  NULL,
    [userField10]          NUMERIC (3)     NULL,
    [globalID1]            VARCHAR (100)   NULL,
    [globalID2]            VARCHAR (255)   NULL,
    [globalID3]            VARCHAR (255)   NULL,
    [globalID4]            VARCHAR (255)   NULL,
    [userDate2]            DATE            NULL,
    [userDate3]            DATE            NULL,
    [userDate4]            DATE            NULL,
    [userDate5]            DATE            NULL,
    [userDate6]            DATE            NULL,
    [userDate7]            DATE            NULL,
    [md_dateLastModified]  DATETIME        NULL,
    [md_etlJob]            INT             NULL,
    [md_etlExecution]      BIGINT          NULL,
    [md_etlRun]            INT             NULL
);

