CREATE TABLE [staging].[FCT_DEP_TIMESHEET] (
    [Id]               INT           NOT NULL,
    [AgreementId]      INT           NULL,
    [EmployeeId]       INT           NULL,
    [LeaveRuleId]      INT           NULL,
    [LeaveId]          INT           NULL,
    [PayCycleId]       INT           NULL,
    [AreaId]           INT           NULL,
    [RosterId]         INT           NULL,
    [JobCode]          VARCHAR (100) NULL,
    [timesheetStart]   DATETIME      NULL,
    [timesheetEnd]     DATETIME      NULL,
    [timesheetHours]   FLOAT (53)    NULL,
    [timesheetCost]    FLOAT (53)    NULL,
    [SourceType]       VARCHAR (10)  NULL,
    [InProgress]       BIT           NULL,
    [RealTime]         BIT           NULL,
    [AutoProcessed]    BIT           NULL,
    [PayApproved]      BIT           NULL,
    [TimeApproved]     BIT           NULL,
    [AutoPayApproved]  BIT           NULL,
    [AutoTimeApproved] BIT           NULL,
    [Exported]         BIT           NULL,
    [Paid]             BIT           NULL,
    [Invoiced]         BIT           NULL,
    [InvoiceComment]   VARCHAR (200) NULL,
    [Discarded]        BIT           NULL,
    [PONumber]         VARCHAR (200) NULL,
    [RITM]             VARCHAR (200) NULL,
    [EMSMinutes]       FLOAT (53)    NULL,
    [NCRMinutes]       FLOAT (53)    NULL,
    [phHours]          FLOAT (53)    NULL,
    [Modified]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

