CREATE TABLE [staging].[GHS_ACTIVITIES] (
    [id]                       BIGINT        NULL,
    [name]                     VARCHAR (MAX) NULL,
    [reference]                VARCHAR (MAX) NULL,
    [notes]                    VARCHAR (MAX) NULL,
    [status]                   VARCHAR (MAX) NULL,
    [type]                     VARCHAR (MAX) NULL,
    [type_category]            VARCHAR (MAX) NULL,
    [start_time]               DATETIME      NULL,
    [finish_time]              DATETIME      NULL,
    [total_duration_seconds]   BIGINT        NULL,
    [scheduled_start_time]     DATETIME      NULL,
    [scheduled_finish_time]    DATETIME      NULL,
    [is_planned]               BIT           NULL,
    [is_favourite]             BIT           NULL,
    [is_round_trip]            BIT           NULL,
    [is_alerted]               BIT           NULL,
    [is_ongoing]               BIT           NULL,
    [is_archived]              BIT           NULL,
    [start_latitude]           FLOAT (53)    NULL,
    [start_longitude]          FLOAT (53)    NULL,
    [start_address]            VARCHAR (MAX) NULL,
    [destination_latitude]     FLOAT (53)    NULL,
    [destination_longitude]    FLOAT (53)    NULL,
    [destination_address]      VARCHAR (MAX) NULL,
    [timer_type]               VARCHAR (MAX) NULL,
    [timer_tod_time]           VARCHAR (MAX) NULL,
    [reminder_threshold]       BIGINT        NULL,
    [timer_interval_minutes]   BIGINT        NULL,
    [dashboard_url]            VARCHAR (MAX) NULL,
    [tracker_url]              VARCHAR (MAX) NULL,
    [created_at]               DATETIME      NULL,
    [updated_at]               DATETIME      NULL,
    [got_in_trouble_at]        DATETIME      NULL,
    [is_followed_up]           BIT           NULL,
    [is_followed_up_completed] BIT           NULL,
    [approval_status]          VARCHAR (MAX) NULL,
    [v_bttn_serial_number]     VARCHAR (MAX) NULL,
    [user_id]                  BIGINT        NULL,
    [organisation_id]          BIGINT        NULL
);

