CREATE TABLE [staging].[LH_AUDIT] (
    [Audit_id]            VARCHAR (MAX) NULL,
    [Application_id]      VARCHAR (MAX) NULL,
    [Score_actual]        VARCHAR (MAX) NULL,
    [Area_id]             VARCHAR (MAX) NULL,
    [Area_location_id]    VARCHAR (MAX) NULL,
    [Area_location_name]  VARCHAR (MAX) NULL,
    [Area_name]           VARCHAR (MAX) NULL,
    [Area_building_id]    VARCHAR (MAX) NULL,
    [Area_building_name]  VARCHAR (MAX) NULL,
    [Score_max]           VARCHAR (MAX) NULL,
    [Score_result]        VARCHAR (MAX) NULL,
    [Template_id]         VARCHAR (MAX) NULL,
    [Template_title]      VARCHAR (MAX) NULL,
    [Title]               VARCHAR (MAX) NULL,
    [Role_id]             VARCHAR (MAX) NULL,
    [Role_name]           VARCHAR (MAX) NULL,
    [User_id]             VARCHAR (MAX) NULL,
    [User_first_name]     VARCHAR (MAX) NULL,
    [User_last_name]      VARCHAR (MAX) NULL,
    [Audit_created_at]    VARCHAR (MAX) NULL,
    [Audit_updated_at]    VARCHAR (MAX) NULL,
    [Footer_group_name]   VARCHAR (MAX) NULL,
    [Footer_field_name]   VARCHAR (MAX) NULL,
    [Footer_field_value]  VARCHAR (MAX) NULL,
    [Footer_field_type]   VARCHAR (MAX) NULL,
    [Header_group_name]   VARCHAR (MAX) NULL,
    [Header_field_name]   VARCHAR (MAX) NULL,
    [Header_field_value]  VARCHAR (MAX) NULL,
    [Header_field_type]   VARCHAR (MAX) NULL,
    [Revision_number]     VARCHAR (MAX) NULL,
    [md_filename]         VARCHAR (MAX) NULL,
    [md_dateLastModified] DATETIME      NULL,
    [md_etlJob]           BIGINT        NULL,
    [md_etlExecution]     BIGINT        NULL,
    [md_etlRun]           BIGINT        NULL
);

