CREATE TABLE [staging].[LH_ISSUE] (
    [Application_id]      VARCHAR (MAX) NULL,
    [Issue_id]            VARCHAR (MAX) NULL,
    [Issue_title]         VARCHAR (MAX) NULL,
    [Issue_updated_at]    VARCHAR (MAX) NULL,
    [Issue_created_at]    VARCHAR (MAX) NULL,
    [Issue_duration]      VARCHAR (MAX) NULL,
    [Issue_location_id]   VARCHAR (MAX) NULL,
    [Issue_status]        VARCHAR (MAX) NULL,
    [Template_id]         VARCHAR (MAX) NULL,
    [Template_name]       VARCHAR (MAX) NULL,
    [Area_id]             VARCHAR (MAX) NULL,
    [Area_name]           VARCHAR (MAX) NULL,
    [Area_location_id]    VARCHAR (MAX) NULL,
    [Area_location_name]  VARCHAR (MAX) NULL,
    [Area_building_id]    VARCHAR (MAX) NULL,
    [Area_building_name]  VARCHAR (MAX) NULL,
    [User_id]             VARCHAR (MAX) NULL,
    [Firstname]           VARCHAR (MAX) NULL,
    [Lastname]            VARCHAR (MAX) NULL,
    [Role_id]             VARCHAR (MAX) NULL,
    [Role_name]           VARCHAR (MAX) NULL,
    [Form_group_label]    VARCHAR (MAX) NULL,
    [Field_label]         VARCHAR (MAX) NULL,
    [Field_value]         VARCHAR (MAX) NULL,
    [Revision_number]     VARCHAR (MAX) NULL,
    [md_filename]         VARCHAR (MAX) NULL,
    [md_dateLastModified] DATETIME      NULL,
    [md_etlJob]           BIGINT        NULL,
    [md_etlExecution]     BIGINT        NULL,
    [md_etlRun]           BIGINT        NULL
);

