CREATE TABLE [staging].[LH_SHIFT] (
    [Username]              VARCHAR (MAX) NULL,
    [Firstname]             VARCHAR (MAX) NULL,
    [Lastname]              VARCHAR (MAX) NULL,
    [User_id]               VARCHAR (MAX) NULL,
    [Shift_id]              VARCHAR (MAX) NULL,
    [Shift_start_time]      VARCHAR (MAX) NULL,
    [Shift_end_time]        VARCHAR (MAX) NULL,
    [Shift_created_at]      VARCHAR (MAX) NULL,
    [Shift_updated_at]      VARCHAR (MAX) NULL,
    [Application_id]        VARCHAR (MAX) NULL,
    [Shift_duration]        VARCHAR (MAX) NULL,
    [End_gps_coordinates]   VARCHAR (MAX) NULL,
    [End_location_id]       VARCHAR (MAX) NULL,
    [End_location_name]     VARCHAR (MAX) NULL,
    [End_geocode_label]     VARCHAR (MAX) NULL,
    [Start_area_name]       VARCHAR (MAX) NULL,
    [Start_area_id]         VARCHAR (MAX) NULL,
    [Start_gps_coordinates] VARCHAR (MAX) NULL,
    [Start_geocode_label]   VARCHAR (MAX) NULL,
    [Role_id]               VARCHAR (MAX) NULL,
    [Revision_number]       VARCHAR (MAX) NULL,
    [md_filename]           VARCHAR (MAX) NULL,
    [md_dateLastModified]   DATETIME      NULL,
    [md_etlJob]             BIGINT        NULL,
    [md_etlExecution]       BIGINT        NULL,
    [md_etlRun]             BIGINT        NULL
);

