CREATE TABLE [staging].[LH_TASK] (
    [Task_id]             VARCHAR (MAX) NULL,
    [Application_id]      VARCHAR (MAX) NULL,
    [Created_at]          VARCHAR (MAX) NULL,
    [Updated_at]          VARCHAR (MAX) NULL,
    [Task_title]          VARCHAR (MAX) NULL,
    [Template_id]         VARCHAR (MAX) NULL,
    [Template_name]       VARCHAR (MAX) NULL,
    [Area_id]             VARCHAR (MAX) NULL,
    [Area_name]           VARCHAR (MAX) NULL,
    [Area_location_id]    VARCHAR (MAX) NULL,
    [Area_location_name]  VARCHAR (MAX) NULL,
    [Area_building_id]    VARCHAR (MAX) NULL,
    [Area_building_name]  VARCHAR (MAX) NULL,
    [User_id]             VARCHAR (MAX) NULL,
    [Firstname]           VARCHAR (MAX) NULL,
    [Lastname]            VARCHAR (MAX) NULL,
    [Role_id]             VARCHAR (MAX) NULL,
    [Role_name]           VARCHAR (MAX) NULL,
    [Form_group_label]    VARCHAR (MAX) NULL,
    [Field_id]            VARCHAR (MAX) NULL,
    [Field_label]         VARCHAR (MAX) NULL,
    [Field_value]         VARCHAR (MAX) NULL,
    [Revision_number]     VARCHAR (MAX) NULL,
    [md_filename]         VARCHAR (MAX) NULL,
    [md_dateLastModified] DATETIME      NULL,
    [md_etlJob]           BIGINT        NULL,
    [md_etlExecution]     BIGINT        NULL,
    [md_etlRun]           BIGINT        NULL
);

