CREATE TABLE [staging].[LKP_IT_ROSTERDETAIL] (
    [assignmentId]           BIGINT           NULL,
    [startTime]              NVARCHAR (255)   NULL,
    [endTime]                NVARCHAR (255)   NULL,
    [lengthHours]            DECIMAL (28, 10) NULL,
    [customerName]           NVARCHAR (255)   NULL,
    [customerRef]            NVARCHAR (255)   NULL,
    [customerCode]           NVARCHAR (255)   NULL,
    [locationName]           NVARCHAR (255)   NULL,
    [locationShortName]      NVARCHAR (255)   NULL,
    [locationRef]            NVARCHAR (255)   NULL,
    [locationCode]           NVARCHAR (255)   NULL,
    [subLocationName]        NVARCHAR (255)   NULL,
    [subLocationShortName]   NVARCHAR (255)   NULL,
    [subLocationRef]         NVARCHAR (255)   NULL,
    [subLocationCode]        NVARCHAR (255)   NULL,
    [activityName]           NVARCHAR (255)   NULL,
    [activityShortName]      NVARCHAR (255)   NULL,
    [activityRef]            NVARCHAR (255)   NULL,
    [activityCode]           NVARCHAR (255)   NULL,
    [unitName]               NVARCHAR (255)   NULL,
    [unitRef]                NVARCHAR (255)   NULL,
    [rankName]               NVARCHAR (255)   NULL,
    [rankRef]                NVARCHAR (255)   NULL,
    [hours]                  DECIMAL (28, 10) NULL,
    [rate]                   DECIMAL (28, 10) NULL,
    [leaveName]              NVARCHAR (255)   NULL,
    [leaveShortName]         NVARCHAR (255)   NULL,
    [leaveCode]              NVARCHAR (255)   NULL,
    [payLeaveName]           NVARCHAR (255)   NULL,
    [hoursModifierName]      NVARCHAR (255)   NULL,
    [hoursModifierShortName] NVARCHAR (255)   NULL,
    [hoursModifierReference] NVARCHAR (255)   NULL,
    [hoursModifierType]      NVARCHAR (255)   NULL,
    [hoursModifierCode]      NVARCHAR (255)   NULL,
    [premium]                DECIMAL (28, 10) NULL,
    [rateMultiplier]         DECIMAL (28, 10) NULL,
    [premiumHoursType]       NVARCHAR (255)   NULL
);

