CREATE TABLE [staging].[PR_PAYROLL_EXCEPTION] (
    [SK_PR_PAYROLL_EXCEPTION] INT          IDENTITY (1, 1) NOT NULL,
    [idNumber]                INT          NULL,
    [payCodeType]             VARCHAR (1)  NULL,
    [payCode]                 VARCHAR (2)  NULL,
    [batchNo]                 INT          NULL,
    [postingDate]             DATETIME     NULL,
    [payrunGroup]             VARCHAR (2)  NULL,
    [costingDate]             DATETIME     NULL,
    [hours]                   REAL         NULL,
    [payRate]                 REAL         NULL,
    [amount]                  REAL         NULL,
    [account]                 VARCHAR (10) NULL,
    [department]              VARCHAR (8)  NULL,
    [sequenceNo]              SMALLINT     NULL,
    [labourCost1]             VARCHAR (10) NULL,
    [labourCost2]             VARCHAR (10) NULL,
    [labourCost3]             VARCHAR (20) NULL,
    [userCost1]               VARCHAR (10) NULL,
    [userCost2]               VARCHAR (10) NULL,
    [userCost3]               VARCHAR (10) NULL,
    [payRateOverride]         REAL         NULL,
    [payDate]                 DATETIME     NULL,
    [leaveUnits]              REAL         NULL,
    [payslipNo]               INT          NULL,
    [md_dateLastModified]     DATETIME     NULL,
    [md_etlJob]               INT          NULL,
    [md_etlExecution]         BIGINT       NULL,
    [md_etlRun]               INT          NULL,
    [paylineId]               VARCHAR (15) NULL,
    [jobMissing]              BIT          NULL,
    [actMissing]              BIT          NULL,
    PRIMARY KEY CLUSTERED ([SK_PR_PAYROLL_EXCEPTION] ASC)
);

