CREATE TABLE [staging].[STG_GT_JOB] (
    [jobCode]               VARCHAR (20)    NOT NULL,
    [jobName]               VARCHAR (120)   NULL,
    [oid_clsno]             INT             NOT NULL,
    [oid_instid]            BIGINT          NOT NULL,
    [oid_parent_clsno]      INT             NULL,
    [oid_parent_instid]     BIGINT          NULL,
    [myProfitCentre_clsno]  INT             NULL,
    [myProfitCentre_instid] BIGINT          NULL,
    [createDate]            DATE            NULL,
    [jobStatus]             VARCHAR (20)    NULL,
    [jobClosed]             BIT             NULL,
    [jobChargeType]         VARCHAR (6)     NULL,
    [jobActivityGroup]      VARCHAR (30)    NULL,
    [jobType]               VARCHAR (6)     NULL,
    [myCustomer_clsno]      INT             NULL,
    [myCustomer_instid]     BIGINT          NULL,
    [salesCodeOverride]     VARCHAR (MAX)   NULL,
    [priceBook_clsno]       INT             NULL,
    [priceBook_instid]      BIGINT          NULL,
    [priceBookCode]         VARCHAR (10)    NULL,
    [ordRate]               DECIMAL (20, 5) NULL,
    [t15Rate]               DECIMAL (20, 5) NULL,
    [payRate]               FLOAT (53)      NULL,
    [lastDocDate]           DATE            NULL,
    [billingGroup]          VARCHAR (30)    NULL,
    [orderNumber]           VARCHAR (30)    NULL,
    [clientReference]       VARCHAR (20)    NULL,
    [jobReference]          VARCHAR (20)    NULL,
    [quoteReference]        VARCHAR (20)    NULL,
    [invoiceReportFormat]   VARCHAR (70)    NULL,
    [jobManager]            VARCHAR (10)    NULL,
    [AXCC]                  VARCHAR (13)    NULL,
    [GroupContract]         VARCHAR (60)    NULL,
    [MajorContract]         VARCHAR (50)    NULL,
    [StaticGuard]           BIT             NULL
);

