CREATE TABLE [staging].[STG_IT_AUDITASSIGNDATA] (
    [assignmentId]           BIGINT         NULL,
    [employeeId]             VARCHAR (50)   NULL,
    [employeeFullName]       VARCHAR (255)  NULL,
    [scheduledStartTime]     NVARCHAR (255) NULL,
    [scheduledEndTime]       NVARCHAR (255) NULL,
    [actualStartTime]        NVARCHAR (255) NULL,
    [actualEndTime]          NVARCHAR (255) NULL,
    [customerName]           VARCHAR (100)  NULL,
    [customerCode]           VARCHAR (50)   NULL,
    [locationName]           VARCHAR (100)  NULL,
    [locationReference]      VARCHAR (50)   NULL,
    [locationCode]           VARCHAR (50)   NULL,
    [activityName]           VARCHAR (100)  NULL,
    [activityReference]      VARCHAR (50)   NULL,
    [activityCode]           VARCHAR (50)   NULL,
    [subLocationReference]   VARCHAR (50)   NULL,
    [subLocationName]        VARCHAR (100)  NULL,
    [subLocationCode]        VARCHAR (50)   NULL,
    [hoursModifierName]      VARCHAR (100)  NULL,
    [hoursModifierShortName] VARCHAR (50)   NULL,
    [hoursModifierReference] VARCHAR (50)   NULL,
    [hoursModifierType]      VARCHAR (50)   NULL,
    [hoursModifierCode]      VARCHAR (50)   NULL,
    [hoursSchedMinHours]     VARCHAR (50)   NULL,
    [hoursActualMinimum]     VARCHAR (50)   NULL,
    [timeBankReference]      VARCHAR (100)  NULL,
    [timeBankName]           VARCHAR (100)  NULL,
    [timeBankShortName]      VARCHAR (50)   NULL,
    [timeBankCode]           VARCHAR (50)   NULL,
    [timeBankHours]          VARCHAR (50)   NULL,
    [rankName]               VARCHAR (100)  NULL,
    [rankReference]          VARCHAR (50)   NULL,
    [unitName]               VARCHAR (100)  NULL,
    [unitReference]          VARCHAR (50)   NULL,
    [note]                   VARCHAR (MAX)  NULL,
    [activityRequestId]      BIGINT         NULL,
    [organizer]              VARCHAR (100)  NULL,
    [modifiedTimeStamp]      VARCHAR (50)   NULL,
    [modifiedUserName]       VARCHAR (50)   NULL,
    [modifiedType]           VARCHAR (50)   NULL,
    [branchName]             VARCHAR (100)  NULL,
    [branchReference]        VARCHAR (100)  NULL,
    [assignDate]             DATE           NULL,
    [assignOrigin]           VARCHAR (50)   NULL,
    [cancelReason]           VARCHAR (100)  NULL,
    [branchid]               INT            NULL
);

