CREATE TABLE [staging].[WS_Despatch] (
    [DespatchId]                      INT             NULL,
    [ClientId]                        INT             NULL,
    [ClientIDCode]                    VARCHAR (128)   NULL,
    [despatchTypeId]                  INT             NULL,
    [DespatchZoneId]                  INT             NULL,
    [PermanentPatrolId]               INT             NULL,
    [MonitoringStationId]             INT             NULL,
    [MonitoringStationDespatcherName] VARCHAR (128)   NULL,
    [PatrolOfficerEmployee1Id]        INT             NULL,
    [DespatchDateTime]                DATETIME        NULL,
    [AckDateTime]                     DATETIME        NULL,
    [OnSiteDateTime]                  DATETIME        NULL,
    [OffSiteDateTime]                 DATETIME        NULL,
    [TimeToRespondInMinutes]          INT             NULL,
    [timeToAcknowledgeInMinutes]      INT             NULL,
    [TimeOnSiteInMinutes]             INT             NULL,
    [ChargeTotalExGST]                NUMERIC (10, 2) NULL,
    [ClientPatrolCharge]              NUMERIC (10, 2) NULL,
    [CasualChargeType]                VARCHAR (14)    NULL,
    [MissedCount]                     INT             NULL,
    [TotalCount]                      INT             NULL,
    [IsIncidentReport]                BIT             NULL,
    [OnsiteDistanceFromSite]          VARCHAR (64)    NULL,
    [OnSiteLat]                       VARCHAR (64)    NULL,
    [OnSiteLong]                      VARCHAR (64)    NULL,
    [responseNoCharge]                BIT             NULL,
    [PurchaseOrderNo]                 VARCHAR (128)   NULL,
    [JobText]                         VARCHAR (MAX)   NULL,
    [SpecialInstructions]             VARCHAR (MAX)   NULL,
    [PatrolResolution]                VARCHAR (MAX)   NULL,
    [PatrolCompleteStatus]            VARCHAR (20)    NULL,
    [HasPhotos]                       BIT             NULL
);

