CREATE TABLE [staging].[WS_Despatch] (
    [DespatchId]                      INT             NULL,
    [AlarmDocketId]                   INT             NULL,
    [KDTNo]                           VARCHAR (16)    NULL,
    [ClientId]                        INT             NULL,
    [ClientIDCode]                    VARCHAR (128)   NULL,
    [despatchTypeId]                  INT             NULL,
    [OtherDocketType]                 INT             NULL,
    [DespatchZoneId]                  INT             NULL,
    [PermanentPatrolId]               INT             NULL,
    [MonitoringStationId]             INT             NULL,
    [MonitoringStationDespatcherName] VARCHAR (128)   NULL,
    [PatrolOfficerEmployee1Id]        INT             NULL,
    [DespatchDateTime]                DATETIME        NULL,
    [AckDateTime]                     DATETIME        NULL,
    [OnSiteDateTime]                  DATETIME        NULL,
    [OffSiteDateTime]                 DATETIME        NULL,
    [FinalOnSiteDateTime]             DATETIME        NULL,
    [FinalOffSiteDateTime]            DATETIME        NULL,
    [TempClientSite]                  VARCHAR (128)   NULL,
    [TempClientAddress1]              VARCHAR (128)   NULL,
    [TempClientAddress2]              VARCHAR (128)   NULL,
    [TempClientSuburbId]              INT             NULL,
    [TimeToRespondInMinutes]          INT             NULL,
    [timeToAcknowledgeInMinutes]      INT             NULL,
    [TimeOnSiteInMinutes]             INT             NULL,
    [ExtraTimeOnSiteInMinutes]        INT             NULL,
    [OverResponseTimeInMinutes]       INT             NULL,
    [ChargeTotalExGST]                NUMERIC (10, 2) NULL,
    [ClientPatrolCharge]              NUMERIC (10, 2) NULL,
    [CasualChargeType]                VARCHAR (14)    NULL,
    [MissedCount]                     INT             NULL,
    [TotalCount]                      INT             NULL,
    [IsIncidentReport]                BIT             NULL,
    [OnsiteDistanceFromSite]          VARCHAR (64)    NULL,
    [AllowedTimeOnSite]               INT             NULL,
    [TimeOnSiteVariationinMinutes]    INT             NULL,
    [OnSiteLat]                       VARCHAR (64)    NULL,
    [OnSiteLong]                      VARCHAR (64)    NULL,
    [FinalOnSiteLat]                  VARCHAR (64)    NULL,
    [FinalOnSiteLong]                 VARCHAR (64)    NULL,
    [responseNoCharge]                BIT             NULL,
    [PurchaseOrderNo]                 VARCHAR (128)   NULL,
    [JobText]                         VARCHAR (MAX)   NULL,
    [SpecialInstructions]             VARCHAR (MAX)   NULL,
    [AlarmComplete]                   BIT             NULL,
    [PatrolResolution]                VARCHAR (MAX)   NULL,
    [PatrolCompleteStatus]            VARCHAR (20)    NULL,
    [HasPhotos]                       BIT             NULL
);

