CREATE TABLE [staging].[WS_PermPatrols] (
    [PermanentPatrolId]        INT           NULL,
    [ClientId]                 INT           NULL,
    [DespatchZoneId]           INT           NULL,
    [PatrolStartDate]          DATETIME      NULL,
    [PatrolEndDate]            DATETIME      NULL,
    [PatrolType]               VARCHAR (9)   NULL,
    [PatrolStatus]             VARCHAR (8)   NULL,
    [PatrolServiceType]        VARCHAR (32)  NULL,
    [PatrolChargeType]         VARCHAR (11)  NULL,
    [PatrolPriceType]          VARCHAR (14)  NULL,
    [patrolName]               VARCHAR (128) NULL,
    [Comments]                 VARCHAR (MAX) NULL,
    [PONumber]                 VARCHAR (128) NULL,
    [PermWeeklyPatrolCount]    INT           NULL,
    [LastDespatchDate]         DATETIME      NULL,
    [NeverCharge]              BIT           NULL,
    [MondayCount]              INT           NULL,
    [MondayTimeAllowed]        INT           NULL,
    [TuesdayCount]             INT           NULL,
    [TuesdayTimeAllowed]       INT           NULL,
    [WednesdayCount]           INT           NULL,
    [WednesdayTimeAllowed]     INT           NULL,
    [ThursdayCount]            INT           NULL,
    [ThursdayTimeAllowed]      INT           NULL,
    [FridayCount]              INT           NULL,
    [FridayTimeAllowed]        INT           NULL,
    [SaturdayCount]            INT           NULL,
    [SaturdayTimeAllowed]      INT           NULL,
    [SundayCount]              INT           NULL,
    [SundayTimeAllowed]        INT           NULL,
    [PublicHolidayCount]       INT           NULL,
    [PublicHolidayTimeAllowed] INT           NULL,
    [ServiceDescription]       VARCHAR (128) NULL
);

