-- Payroll Extract Code
DECLARE					@eventId int = 6337;

SELECT					t.Id,
						t.AgreementId,
						t.EmployeeId,
						t.LeaveRuleId,
						t.LeaveLineId,
						t.PayCycleId,
						t.AreaId,
						t.JobCode,
						t.activityCode,
						t.timesheetStart,
						t.timesheetEnd,
						t.timesheetHours,
						t.timesheetCost,
						t.sourceType,
						t.InProgress,
						t.RealTime,
						t.AutoProcessed,
						t.PayApproved,
						t.TimeApproved,
						t.AutoPayApproved,
						t.AutoTimeApproved,
						t.Exported,
						t.emsminutes,
						t.ncrminutes,
						isnull(t.ponumber, t.sourcePO) ponumber,
						isnull(t.ritm,t.sorceRITM) ritm,
						t.lineCost,
						t.lineHours,
						t.Overridden,
						t.OverrideComment,
						t.PayTitle,
						t.PayActivityCode,
						t.BaseRate,
						t.SiteRate,
						t.ClientTierRate,
						t.phHours,
						t.altCredit,
						t.phRef,
						t.MDEventId
FROM					eda.EXT_DEP_FULL t
WHERE					t.MDEventId = @eventId;